import {PRODUCTS,SLOTS,productById} from './cosmetics.js';
import {mkdir,readFile} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {createHash} from 'node:crypto';
export class AccountError extends Error{constructor(message,status=409){super(message);this.status=status;}}
export function normalizedNickname(value){const name=typeof value==='string'?value.normalize('NFC').trim():'';if(!/^[가-힣a-zA-Z0-9]{2,12}$/.test(name))throw new AccountError('닉네임은 한글·영문·숫자 2~12자로 입력하세요.',400);return name;}
const schema=[
`CREATE TABLE IF NOT EXISTS login_sessions (token_hash TEXT PRIMARY KEY, account_id TEXT NOT NULL, expires_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS cosmetic_ownership (account_id TEXT NOT NULL, item_id TEXT NOT NULL, acquired_at TEXT NOT NULL, PRIMARY KEY(account_id,item_id))`,
`CREATE TABLE IF NOT EXISTS cosmetic_equipment (account_id TEXT NOT NULL, slot TEXT NOT NULL, item_id TEXT NOT NULL, PRIMARY KEY(account_id,slot))`,

`CREATE TABLE IF NOT EXISTS diamond_rewards (id TEXT PRIMARY KEY, account_id TEXT NOT NULL, amount INTEGER NOT NULL CHECK(amount>0), date TEXT NOT NULL)`,
`CREATE INDEX IF NOT EXISTS diamond_account_idx ON diamond_rewards(account_id)`,

`CREATE TABLE IF NOT EXISTS account_profiles (id TEXT PRIMARY KEY, nickname TEXT, nickname_key TEXT UNIQUE, lobby_card INTEGER NOT NULL DEFAULT 0 CHECK(lobby_card BETWEEN 0 AND 19), created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS battle_results (id TEXT PRIMARY KEY, account_id TEXT, name TEXT NOT NULL, mode TEXT NOT NULL, hard INTEGER NOT NULL, random INTEGER NOT NULL, round INTEGER NOT NULL, kills INTEGER NOT NULL, seconds INTEGER NOT NULL, date TEXT NOT NULL)`,
`CREATE INDEX IF NOT EXISTS battle_rank_idx ON battle_results(round DESC,hard DESC,kills DESC)`,
`CREATE INDEX IF NOT EXISTS battle_account_idx ON battle_results(account_id,date DESC)`,
`CREATE TABLE IF NOT EXISTS storage_migrations (id TEXT PRIMARY KEY, applied_at TEXT NOT NULL)`];
export async function openAccountStore({databaseUrl=process.env.DATABASE_URL,dir=process.env.DATA_DIR||'data',render=process.env.RENDER,autoImport=true}={}){
 if(render&&!databaseUrl)throw new Error('Render에서는 DATABASE_URL 설정이 필요합니다. 임시 디스크로 계정 데이터를 저장하지 않습니다.');
 let query,close,backup,transaction,kind;
 if(databaseUrl){const {Pool}=await import('pg');const pool=new Pool({connectionString:databaseUrl,max:5,connectionTimeoutMillis:5000,statement_timeout:10000});pool.on('error',()=>console.error('Account database connection error'));query=async(sql,args=[])=>{const r=await pool.query(sql,args);return r.rows;};transaction=async fn=>{const c=await pool.connect();try{await c.query('BEGIN');const result=await fn(async(sql,args=[])=>{const r=await c.query(sql,args);return r.rows;});await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}};close=()=>pool.end();kind='postgres';
 }else{const {DatabaseSync,backup:sqliteBackup}=await import('node:sqlite');await mkdir(dir,{recursive:true});const db=new DatabaseSync(resolve(dir,'accounts.sqlite'));db.exec('PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA busy_timeout=5000;');const raw=async(sql,args=[])=>db.prepare(sql.replace(/\$\d+/g,'?')).all(...args);let tail=Promise.resolve();query=(...args)=>{const work=tail.then(()=>raw(...args));tail=work.catch(()=>{});return work;};transaction=fn=>{const work=tail.then(async()=>{db.exec('BEGIN IMMEDIATE');try{const result=await fn(raw);db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}});tail=work.catch(()=>{});return work;};close=async()=>{await tail;db.close();};backup=async path=>{await tail;await mkdir(dirname(path),{recursive:true});await sqliteBackup(db,path);};kind='sqlite';}
 try{for(const sql of schema)await query(sql);}catch(e){await close();throw e;}
 // Expand the existing persisted constraint as well as fresh databases.
 await transaction(async q=>{if((await q("SELECT id FROM storage_migrations WHERE id='lobby-cards-20-v1'")).length)return;
 if(kind==='postgres'){await q('ALTER TABLE account_profiles DROP CONSTRAINT IF EXISTS account_profiles_lobby_card_check');await q('ALTER TABLE account_profiles ADD CONSTRAINT account_profiles_lobby_card_check CHECK(lobby_card BETWEEN 0 AND 19)');}
 else{await q(schema.find(sql=>sql.startsWith('CREATE TABLE IF NOT EXISTS account_profiles ')).replace('account_profiles (','account_profiles_expanded ('));await q('INSERT INTO account_profiles_expanded SELECT * FROM account_profiles');await q('DROP TABLE account_profiles');await q('ALTER TABLE account_profiles_expanded RENAME TO account_profiles');}
 await q('INSERT INTO storage_migrations(id,applied_at) VALUES($1,$2)',['lobby-cards-20-v1',new Date().toISOString()]);});
 const now=()=>new Date().toISOString();
 const store={kind,close,backup,
 async cosmetics(id){const owned=await query('SELECT item_id FROM cosmetic_ownership WHERE account_id=$1',[id]);const equipment=await query('SELECT slot,item_id FROM cosmetic_equipment WHERE account_id=$1',[id]);return {owned:owned.map(r=>r.item_id),equipped:Object.fromEntries(equipment.map(r=>[r.slot,r.item_id]))};},
 async purchaseCosmetic(id,item){const p=productById(item);if(!p||p.price!==0)throw new AccountError('구매할 수 없는 상품입니다.',400);await transaction(async q=>{const user=await q('SELECT id FROM account_profiles WHERE id=$1',[id]);if(!user.length)throw new AccountError('계정을 찾을 수 없습니다.',404);await q('INSERT INTO cosmetic_ownership(account_id,item_id,acquired_at) VALUES($1,$2,$3) ON CONFLICT(account_id,item_id) DO NOTHING',[id,p.id,now()]);});return store.cosmetics(id);},
 async equipCosmetic(id,slot,item){if(!Object.hasOwn(SLOTS,slot))throw new AccountError('올바른 장착 부위를 선택하세요.',400);await transaction(async q=>{if(item===null){await q('DELETE FROM cosmetic_equipment WHERE account_id=$1 AND slot=$2',[id,slot]);return;}const p=productById(item);if(!p||p.slot!==slot)throw new AccountError('장착 부위가 다릅니다.',400);const owned=await q('SELECT item_id FROM cosmetic_ownership WHERE account_id=$1 AND item_id=$2',[id,item]);if(!owned.length)throw new AccountError('먼저 상품을 구매하세요.',403);await q('INSERT INTO cosmetic_equipment(account_id,slot,item_id) VALUES($1,$2,$3) ON CONFLICT(account_id,slot) DO UPDATE SET item_id=excluded.item_id',[id,slot,item]);});return store.cosmetics(id);},

 async diamonds(id){const rows=await query('SELECT COALESCE(SUM(amount),0) AS balance FROM diamond_rewards WHERE account_id=$1',[id]);return Number(rows[0].balance);},
 async grantDiamonds(battleId,rewards){await transaction(async q=>{for(const r of rewards)await q('INSERT INTO diamond_rewards(id,account_id,amount,date) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO NOTHING',[battleId+':'+r.key+':'+r.accountId,r.accountId,r.amount,now()]);});},

 async exportData(){return transaction(async q=>{const p=await q('SELECT id,nickname,lobby_card FROM account_profiles');const r=await q('SELECT id,account_id,name,mode,hard,random,round,kills,seconds,date FROM battle_results ORDER BY date');const diamonds=await q('SELECT id,account_id,amount,date FROM diamond_rewards');const cosmetics={owned:await q('SELECT * FROM cosmetic_ownership'),equipped:await q('SELECT * FROM cosmetic_equipment')};return {cosmetics,diamonds,profiles:Object.fromEntries(p.map(p=>[p.id,{nickname:p.nickname,lobbyCard:p.lobby_card}])),rankings:r.map(r=>({...r,accountId:r.account_id,random:!!r.random}))};});},
 async getProfile(id){const rows=await query('SELECT * FROM account_profiles WHERE id=$1',[id]);const p=rows[0];return p?{id:p.id,nickname:p.nickname,lobbyCard:p.lobby_card}:null;},
 async ensureProfile(id){const date=now();await query('INSERT INTO account_profiles(id,created_at,updated_at) VALUES($1,$2,$3) ON CONFLICT(id) DO NOTHING',[id,date,date]);return store.getProfile(id);},
 async nicknameAvailable(id,value){const name=normalizedNickname(value);const r=await query('SELECT id FROM account_profiles WHERE nickname_key=$1 AND id<>$2',[name.toLowerCase(),id]);return !r.length;},
 async setNickname(id,value){const name=normalizedNickname(value);try{const rows=await query('UPDATE account_profiles SET nickname=$1,nickname_key=$2,updated_at=$3 WHERE id=$4 AND nickname IS NULL RETURNING id',[name,name.toLowerCase(),now(),id]);if(!rows.length)throw new AccountError('이미 닉네임을 생성했거나 계정을 찾을 수 없습니다.');}catch(e){if(e.code==='23505'||String(e.message).includes('UNIQUE constraint'))throw new AccountError('이미 사용 중인 닉네임입니다.');throw e;}return store.getProfile(id);},
 async setCard(id,card){if(!Number.isInteger(card)||card<0||card>=20)throw new AccountError('올바른 캐릭터 카드를 선택하세요.',400);const r=await query('UPDATE account_profiles SET lobby_card=$1,updated_at=$2 WHERE id=$3 RETURNING id',[card,now(),id]);if(!r.length)throw new AccountError('계정을 찾을 수 없습니다.',404);return store.getProfile(id);},
 async saveSession(token,accountId){await query('INSERT INTO login_sessions(token_hash,account_id,expires_at) VALUES($1,$2,$3)',[createHash('sha256').update(token).digest('hex'),accountId,new Date(Date.now()+30*86400000).toISOString()]);},
 async restoreSession(token){if(!token)return null;const rows=await query('SELECT account_id FROM login_sessions WHERE token_hash=$1 AND expires_at>$2',[createHash('sha256').update(token).digest('hex'),now()]);return rows.length?store.getProfile(rows[0].account_id):null;},
 async revokeSessions(id){await query('DELETE FROM login_sessions WHERE account_id=$1',[id]);},
 async rankings(){const rows=await query('SELECT account_id,name,mode,hard,random,round,kills,seconds,date FROM (SELECT *,ROW_NUMBER() OVER (PARTITION BY COALESCE(account_id,name) ORDER BY round DESC,hard DESC,kills DESC,date DESC,id DESC) AS rank_no FROM battle_results) best WHERE rank_no=1 ORDER BY round DESC,hard DESC,kills DESC,date DESC LIMIT 200');const ids=[...new Set(rows.map(r=>r.account_id).filter(Boolean))],decorations=new Map();for(const id of ids)decorations.set(id,(await store.cosmetics(id)).equipped);return rows.map(({account_id,...r})=>({...r,random:!!r.random,cosmetics:decorations.get(account_id)||{}}));},
 async history(id){return (await query('SELECT name,mode,hard,random,round,kills,seconds,date FROM battle_results WHERE account_id=$1 ORDER BY date DESC LIMIT 50',[id])).map(r=>({...r,random:!!r.random}));},
 async recordBattle(battleId,records){await transaction(async q=>{for(const r of records)await insertResult(q,battleId+':'+r.accountId,r);});}
 };
 async function insertResult(q,id,r){await q('INSERT INTO battle_results(id,account_id,name,mode,hard,random,round,kills,seconds,date) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(id) DO NOTHING',[id,r.accountId||null,r.name,r.mode,r.hard,r.random?1:0,r.round,r.kills,r.seconds,r.date]);}
 store.importLegacy=async()=>{
 const done=await query('SELECT id FROM storage_migrations WHERE id=$1',['legacy-json-v1']);if(done.length)return;
 const read=async file=>{try{return JSON.parse(await readFile(resolve(dir,file),'utf8'));}catch(e){if(e.code==='ENOENT')return null;throw new Error('기존 '+file+' 파일을 읽을 수 없습니다. 원본 확인 후 다시 시작하세요.');}};
 const cosmetics=await read('cosmetics.json');if(cosmetics&&(!Array.isArray(cosmetics.owned)||!Array.isArray(cosmetics.equipped)))throw Error('cosmetics.json 형식 오류');const diamonds=await read('diamonds.json');const profiles=await read('profiles.json'),rankings=await read('rankings.json');if(diamonds!==null&&!Array.isArray(diamonds))throw Error('diamonds.json 형식 오류');if(profiles!==null&&(typeof profiles!=='object'||Array.isArray(profiles)))throw Error('profiles.json 형식 오류');if(rankings!==null&&!Array.isArray(rankings))throw Error('rankings.json 형식 오류');
 await transaction(async q=>{for(const r of cosmetics?.owned||[]){if(!productById(r.item_id)||typeof r.account_id!=='string'||typeof r.acquired_at!=='string')throw Error('꾸미기 보유 기록 오류');await q('INSERT INTO cosmetic_ownership(account_id,item_id,acquired_at) VALUES($1,$2,$3) ON CONFLICT(account_id,item_id) DO NOTHING',[r.account_id,r.item_id,r.acquired_at]);}for(const r of cosmetics?.equipped||[]){if(productById(r.item_id)?.slot!==r.slot||!cosmetics.owned.some(o=>o.account_id===r.account_id&&o.item_id===r.item_id))throw Error('꾸미기 장착 기록 오류');await q('INSERT INTO cosmetic_equipment(account_id,slot,item_id) VALUES($1,$2,$3) ON CONFLICT(account_id,slot) DO NOTHING',[r.account_id,r.slot,r.item_id]);}for(const r of diamonds||[]){if(typeof r.id!=='string'||typeof r.account_id!=='string'||!Number.isSafeInteger(r.amount)||r.amount<=0||typeof r.date!=='string')throw Error('다이아 기록 형식 오류');await q('INSERT INTO diamond_rewards(id,account_id,amount,date) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO NOTHING',[r.id,r.account_id,r.amount,r.date]);}for(const [id,p]of Object.entries(profiles||{})){if(!id.startsWith('g_'))continue;const nickname=p.nickname?normalizedNickname(p.nickname):null;const card=p.lobbyCard??0;if(!Number.isInteger(card)||card<0||card>19)throw Error('기존 카드 값 오류');await q('INSERT INTO account_profiles(id,nickname,nickname_key,lobby_card,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(id) DO NOTHING',[id,nickname,nickname?.toLowerCase()||null,card,now(),now()]);}for(const [i,r]of (rankings||[]).entries()){if(!r||typeof r.name!=='string'||!['single','coop','versus'].includes(r.mode)||!['hard','round','kills','seconds'].every(k=>Number.isSafeInteger(r[k])&&r[k]>=0)||typeof r.date!=='string')throw Error('기존 전투 기록 형식 오류');const key=createHash('sha256').update(JSON.stringify([i,r])).digest('hex');await insertResult(q,r.id||'legacy:'+key,r);}await q('INSERT INTO storage_migrations(id,applied_at) VALUES($1,$2) ON CONFLICT(id) DO NOTHING',['legacy-json-v1',now()]);});
 };
 try{if(autoImport)await store.importLegacy();return store;}catch(e){await close();throw e;}
}
