import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {openAccountStore} from './account-store.mjs';
async function fixture(){const dir=await mkdtemp(join(tmpdir(),'loop-store-'));return {dir,store:await openAccountStore({dir,databaseUrl:'',render:false})};}
test('profile and match survive reopen; battle retry is idempotent',async()=>{const {dir,store}=await fixture();await store.ensureProfile('g_a');await store.setNickname('g_a','수호자A');await store.setCard('g_a',14);const rows=[{accountId:'g_a',name:'수호자A',mode:'coop',hard:2,random:false,round:50,kills:300,seconds:500,date:new Date().toISOString()}];await store.recordBattle('battle',rows);await store.recordBattle('battle',rows);await store.close();const next=await openAccountStore({dir,databaseUrl:'',render:false});assert.deepEqual(await next.getProfile('g_a'),{id:'g_a',nickname:'수호자A',lobbyCard:14});assert.equal((await next.history('g_a')).length,1);assert.equal((await next.rankings()).length,1);await next.close();});
test('concurrent case-insensitive duplicate names and repeated registration are rejected',async()=>{const {store}=await fixture();await Promise.all(['g_a','g_b'].map(id=>store.ensureProfile(id)));const r=await Promise.allSettled([store.setNickname('g_a','Guardian'),store.setNickname('g_b','guardian')]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);const winner=r[0].status==='fulfilled'?'g_a':'g_b';await assert.rejects(store.setNickname(winner,'다른이름'));await assert.rejects(store.setCard(winner,15));await store.close();});
test('legacy migration preserves original files and only runs once',async()=>{const dir=await mkdtemp(join(tmpdir(),'loop-import-')),original=JSON.stringify({g_a:{nickname:'기존수호자',lobbyCard:3}});await writeFile(join(dir,'profiles.json'),original);let s=await openAccountStore({dir,databaseUrl:'',render:false});assert.equal((await s.getProfile('g_a')).nickname,'기존수호자');await s.setCard('g_a',5);await s.close();s=await openAccountStore({dir,databaseUrl:'',render:false});assert.equal((await s.getProfile('g_a')).lobbyCard,5);assert.equal(await readFile(join(dir,'profiles.json'),'utf8'),original);await s.close();});
test('invalid legacy JSON blocks startup instead of silently discarding accounts',async()=>{const dir=await mkdtemp(join(tmpdir(),'loop-corrupt-'));await writeFile(join(dir,'profiles.json'),'{broken');await assert.rejects(openAccountStore({dir,databaseUrl:'',render:false}),/profiles.json/);});
test('partial battle batch is rolled back on invalid row',async()=>{const {store}=await fixture();const row={accountId:'g_a',name:'a',mode:'single',hard:0,random:false,round:1,kills:1,seconds:1,date:'2026-01-01'};await assert.rejects(store.recordBattle('broken',[row,{...row,accountId:'g_b',name:null}]));assert.equal((await store.rankings()).length,0);await store.close();});
test('SQLite live backup restores account data',async()=>{const {dir,store}=await fixture();await store.ensureProfile('g_a');await store.setNickname('g_a','백업수호자');const restored=join(dir,'restore');await store.backup(join(restored,'accounts.sqlite'));const copy=await openAccountStore({dir:restored,databaseUrl:'',render:false});assert.equal((await copy.getProfile('g_a')).nickname,'백업수호자');await copy.close();await store.close();});
test('Render never falls back to an ephemeral local database',async()=>{await assert.rejects(openAccountStore({databaseUrl:'',render:'true'}),/DATABASE_URL/);});
test('export and migration retain account ownership and battle deduplication',async()=>{
 const {store}=await fixture();
 await store.ensureProfile('g_export');await store.setNickname('g_export','이전수호자');await store.setCard('g_export',7);
 const row={accountId:'g_export',name:'이전수호자',mode:'coop',hard:1,random:true,round:30,kills:200,seconds:120,date:'2026-09-30T00:00:00.000Z'};
 await store.recordBattle('exported-battle',[row]);const data=await store.exportData();await store.close();
 const dir=await mkdtemp(join(tmpdir(),'loop-export-'));
 await writeFile(join(dir,'profiles.json'),JSON.stringify(data.profiles));await writeFile(join(dir,'rankings.json'),JSON.stringify(data.rankings));
 const restored=await openAccountStore({dir,databaseUrl:'',render:false});
 try{assert.deepEqual(await restored.getProfile('g_export'),{id:'g_export',nickname:'이전수호자',lobbyCard:7});await restored.recordBattle('exported-battle',[row]);const history=await restored.history('g_export');assert.equal(history.length,1);assert.equal(history[0].random,true);assert.equal(history[0].kills,200);}finally{await restored.close();}
});
