import { portraitMarkup, CHARACTER_ATLAS } from './art.js';
import { installBattleTools, updateCombat, announceWave } from './battle-ui.js';
import { ArenaRenderer, openAnimationPreview } from './renderer.js';
const arenaRenderer = new ArenaRenderer();
let selectedEnemy = null;
import {TIERS,COLORS,TYPES,CHAMPIONS,ITEMS,SLOTS,chances,stats,position} from './engine.js';
const $=s=>document.querySelector(s),content=$('#content'),icons=['⌖','➶','⚔','❄','♨','◆','≋','☣','✹','✦'];
const modeNames={single:'싱글 디펜스',coop:'협동 디펜스',versus:'대전 디펜스'};
const abilities=['긴 사거리의 강력한 단발 공격','빠른 공격속도와 안정적인 화력','짧은 사거리, 묵직한 근접 피해','적 둔화 · 유니크 이상 빙결','강력한 화염 · 유니크 이상 범위 공격','적 기절 · 유니크 이상 범위 기절','빠른 연사 · 유니크 이상 주변 공속 +25%','중첩되지 않는 지속 독 피해','유니크 이상 범위 폭발 및 추가 피해','직접 처치할 때마다 공격력 영구 성장'];
const effects=['공격력 증가','공격속도 증가','사거리 증가','치명타 확률 증가','치명타 배율 증가','물리 방어관통','마법 방어관통','공격대상 수 증가','둔화 부여','방어 저항 감소'];
let user=null,page='play',options={mode:'single',random:false,hard:0,capacity:2},room=null,game=null,events=null,selected=null,selectedIds=[],selectedItem=null,viewBoard=0,toastTimer,filter='',filterType='all',catalogTier=0,connected=false,dragStart=null,dragNow=null;
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
async function api(path,body){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'서버 요청 실패');return data;}
function me(){return game?.players.find(p=>p.id===user?.id);}
async function act(a){try{await api('action',a);return true;}catch(e){toast(e.message);return false;}}
function setUser(u){user=u;$('#user-name').textContent=u?.name||'게스트 수호자';$('#account-kind').textContent=u?(u.google?'Google 계정 연결됨':'게스트 세션'):'로그인이 필요합니다';$('#login-open').textContent=u?'계정 변경 ↗':'계정 연결 ↗';}
function heading(title,sub,label='PLAY YOUR STRATEGY'){return `<div class="page-heading"><div><span class="eyebrow">${label}</span><h1>${title}</h1><p>${sub}</p></div><span class="season">SEASON 00 · THE FIRST LOOP</span></div>`;}
function home(){window.scrollTo(0,0);content.innerHTML=heading('끝없는 궤도, 당신의 방어선','챔피언을 소환하고, 조합을 완성하고, 100번째 라운드에 도전하세요.')+`<section class="hero"><div class="hero-copy"><span class="badge">TACTICAL RANDOM DEFENSE</span><h2>한 번의 소환.<br><em>무한한 가능성.</em></h2><p>같은 길을 도는 적들, 매번 달라지는 전략.<br>당신만의 챔피언 조합으로 마지막 웨이브까지.</p><div class="hero-tags"><span>◈ 100개의 라운드</span><span>♜ 100종의 챔피언</span><span>◇ 7단계의 등급</span></div></div><canvas class="hero-art" id="hero-canvas" width="650" height="400" aria-label="생성 이미지로 만든 판타지 챔피언들"></canvas></section><div class="section-head"><h2>플레이 모드</h2><span>함께할 방식을 선택하세요</span><span class="right">01 — SELECT MODE</span></div><div class="modes">${['single','coop','versus'].map((m,i)=>`<button data-mode="${m}" class="mode-card ${options.mode===m?'selected':''}"><span class="check">${options.mode===m?'●':'○'}</span><span class="mode-icon">${['♜','♜♜','⚔'][i]}</span><h3>${modeNames[m]}</h3><span class="count">${i?'2 / 4 PLAYERS':'SOLO'}</span><p>${['나만의 속도로 완성하는 전략.<br>전멸 즉시, 또는 60초마다 다음 웨이브.','하나의 전장, 함께 만드는 승리.<br>커다란 맵에서 골드와 전선을 공유하세요.','상대보다 빠르게, 끝까지 살아남기.<br>먼저 끝낸 라운드가 모두의 다음 웨이브로.'][i]}</p></button>`).join('')}</div><div class="setup"><section class="settings"><div class="settings-row"><div><label>몬스터 출현 규칙</label><small>클래식은 고정, 랜덤은 매번 새로운 적</small></div><div class="segments"><button data-random="false" class="${!options.random?'selected':''}">클래식</button><button data-random="true" class="${options.random?'selected':''}">랜덤</button></div></div><div class="settings-row"><div><label>도전 난이도</label><small>하드 단계마다 체력과 방어속성 증가</small></div><select id="difficulty" aria-label="난이도">${['일반 모드','하드 I','하드 II','하드 III','하드 IV','하드 V'].map((s,i)=>`<option value="${i}" ${options.hard===i?'selected':''}>${s}</option>`).join('')}</select></div>${options.mode!=='single'?`<div class="settings-row"><label>플레이어 수</label><div class="segments"><button data-capacity="2" class="${options.capacity===2?'selected':''}">2인</button><button data-capacity="4" class="${options.capacity===4?'selected':''}">4인</button></div></div>`:''}</section><section class="deploy"><div><span class="label">READY TO DEPLOY</span><h3>${modeNames[options.mode]}</h3><p>${options.random?'랜덤':'클래식'} · ${options.hard?'하드 '+options.hard+'단계':'일반 모드'} · 시작 골드 60 G</p></div><button class="primary" id="deploy">${options.mode==='single'?'전투 준비':'대기실 만들기'}<span>→</span></button></section></div><div class="footer-notes"><span>↻ 라운드당 30마리 출현</span><span>⚑ 60초마다 웨이브 · 100마리 누적 패배</span><span>⌁ 소환 · 장비 뽑기 30 G</span></div>${options.mode!=='single'?'<div class="section-head"><h2>공개 대기실</h2><button class="mini-btn right" id="refresh-rooms">새로고침 ↻</button></div><div id="rooms" class="room-list"></div>':''}`;drawHero();if(options.mode!=='single')loadRooms();}
function drawHero(){const cv=$('#hero-canvas');if(!cv)return;const ctx=cv.getContext('2d');ctx.clearRect(0,0,650,400);ctx.save();ctx.translate(325,198);ctx.scale(1,.58);ctx.rotate(-Math.PI/4);ctx.fillStyle='#0d151a';ctx.shadowColor='#a4ff6030';ctx.shadowBlur=45;ctx.fillRect(-160,-160,320,320);ctx.shadowBlur=0;ctx.lineWidth=35;ctx.strokeStyle='#2c3d38';ctx.strokeRect(-168,-168,336,336);ctx.lineWidth=1;ctx.strokeStyle='#72905e';ctx.strokeRect(-189,-189,378,378);ctx.strokeStyle='#627c543f';for(let i=-140;i<=140;i+=35){ctx.beginPath();ctx.moveTo(i,-145);ctx.lineTo(i,145);ctx.stroke();ctx.beginPath();ctx.moveTo(-145,i);ctx.lineTo(145,i);ctx.stroke();}for(let i=0;i<22;i++){let a=i/22*4,x,y;if(a<1){x=-168+336*a;y=-168;}else if(a<2){x=168;y=-168+336*(a-1);}else if(a<3){x=168-336*(a-2);y=168;}else{x=-168;y=168-336*(a-3);}ctx.fillStyle=i%6===0?'#d5b78a':'#89917c';ctx.fillRect(x-7,y-7,14,14);}for(const [x,y,col]of [[-60,-55,'#b9f66d'],[80,0,'#73cccb'],[-30,90,'#bb9aff']]){ctx.fillStyle=col+'18';ctx.beginPath();ctx.arc(x,y,70,0,Math.PI*2);ctx.fill();ctx.strokeStyle=col+'55';ctx.stroke();ctx.fillStyle=col;ctx.shadowColor=col;ctx.shadowBlur=18;ctx.fillRect(x-14,y-14,28,28);ctx.shadowBlur=0;ctx.strokeStyle=col;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(168,y);ctx.stroke();}ctx.restore();ctx.fillStyle='#bad09a';ctx.font='10px monospace';ctx.fillText('SECTOR 01 / SQUARE LOOP',325,369);const art=new Image();art.onload=()=>{if(!cv.isConnected)return;ctx.clearRect(0,0,650,400);ctx.drawImage(art,art.width*2/5,0,art.width*3/5,art.height/2,0,0,650,400);const shade=ctx.createLinearGradient(0,0,200,0);shade.addColorStop(0,'#172221');shade.addColorStop(1,'#17222100');ctx.fillStyle=shade;ctx.fillRect(0,0,650,400);};art.src=CHARACTER_ATLAS;}
async function loadRooms(){try{if(!user){$('#rooms').innerHTML='<div class="empty">로그인 후 대기실에 입장할 수 있습니다.</div>';return;}const list=await api('rooms');if(!$('#rooms'))return;$('#rooms').innerHTML=list.length?list.map(r=>`<div class="room-row"><span>◈</span><div><strong>${esc(r.name)}</strong><p class="muted" style="margin:5px 0 0">${modeNames[r.mode]} · ${r.random?'랜덤':'클래식'} · ${r.hard?'하드 '+r.hard:'일반'} · ${r.players.length}/${r.capacity}인</p></div><button data-join="${r.id}" ${r.status!=='waiting'||r.players.length>=r.capacity?'disabled':''}>${r.status==='waiting'?'입장하기 →':'게임 진행 중'}</button></div>`).join(''):'<div class="empty">아직 열린 대기실이 없습니다. 첫 번째 방을 만들어보세요.</div>';}catch(e){toast(e.message);}}
function subscribe(){events?.close();events=new EventSource('/api/events');events.onmessage=e=>{connected=true;const data=JSON.parse(e.data),wasGame=!!game;room=data.room;const previousRound=game?.round||0;game=data.game;if(game){if(!wasGame||!$('#arena'))battle();arenaRenderer.receive(game);updateBattle();if(game.round>previousRound)announceWave(game.round,game.round%10===0);}else waiting();};events.onerror=()=>{connected=false;updateBattle();toast('서버 연결이 끊겼습니다. 자동으로 재연결합니다.');};}
function waiting(){content.innerHTML=`<div class="waiting"><span class="eyebrow">WAITING FOR GUARDIANS</span><h1 style="margin-top:15px">함께할 수호자를 기다리는 중</h1><p class="muted">같은 서버 주소에 접속하여 공개 대기실에서 이 방에 입장하세요.</p><div class="room-code">${room.id}</div><p>${modeNames[room.mode]} · ${room.random?'랜덤':'클래식'} · ${room.hard?'하드 '+room.hard:'일반'}</p><div class="players-wait">${Array.from({length:room.capacity},(_,i)=>`<div class="player-wait"><span class="champ-icon">${room.players[i]?'♜':'+'}</span><p style="margin:12px 0 0">${esc(room.players[i]?.name||'입장 대기 중')}</p><small class="muted">${i===0?'방장':room.players[i]?'준비 완료':'빈 자리'}</small></div>`).join('')}</div>${room.host===user.id?`<button class="primary" data-action="launch" ${room.players.length<room.capacity?'disabled':''}>챔피언 준비 시작 <span>→</span></button>`:'<p class="muted">방장이 시작하기를 기다리고 있습니다.</p>'}<button id="leave" style="margin-top:15px">대기실 나가기</button></div>`;}
function catalog(kind){const hero=kind==='collection';content.innerHTML=heading(hero?'챔피언 도감':'장비 도감',hero?'10가지 전투 계열, 100종의 챔피언. 모든 챔피언은 7등급으로 성장합니다.':'4가지 장착 부위, 부위별 10종의 장비. 원하는 능력으로 조합을 완성하세요.','BUILD YOUR COLLECTION')+`<div class="filters"><input id="search" placeholder="${hero?'챔피언':'장비'} 이름 검색" value="${esc(filter)}"><select id="filter-type" aria-label="계열 필터"><option value="all">모든 ${hero?'계열':'부위'}</option>${(hero?TYPES:SLOTS).map((t,i)=>`<option value="${i}" ${filterType===String(i)?'selected':''}>${t}</option>`).join('')}</select><select id="catalog-tier" aria-label="등급 필터">${TIERS.map((t,i)=>`<option value="${i}" ${catalogTier===i?'selected':''}>${t}</option>`).join('')}</select></div><div id="catalog-grid" class="catalog"></div>`;catalogGrid(kind);}
function catalogGrid(kind){const hero=kind==='collection',list=(hero?CHAMPIONS:ITEMS).filter(c=>c.name.includes(filter)&&(filterType==='all'||(hero?c.type:c.slot)===Number(filterType)));$('#catalog-grid').innerHTML=list.map(c=>{const s=hero?stats({base:c.id,tier:catalogTier,equipment:{}}):null;return `<article class="catalog-card ${hero?'character-card':'item-card'}">${hero?portraitMarkup(c.type,'catalog-portrait',Math.floor(c.id/10)):''}<span class="champ-icon" style="color:${COLORS[catalogTier]}">${hero?icons[c.type]:['⚔','✥','♧','◇'][c.slot]}</span><h3>${c.name}</h3><p style="color:${COLORS[catalogTier]}">${TIERS[catalogTier]} · ${hero?TYPES[c.type]:SLOTS[c.slot]}</p><p>${hero?abilities[c.type]:effects[c.effect]+' · 등급별 효과 ×1.6'}</p>${hero?`<p>공격 ${s.attack.toFixed(1)} · 공속 ${s.speed} · 사거리 ${s.range}<br>치명 ${(s.crit*100).toFixed(0)}% / ×${s.critMult} · 대상 ${s.targets}</p>`:''}${hero?`<button class="preview-attack" data-preview="${c.id}">공격 모션 보기 ↗</button>`:''}</article>`;}).join('')||'<div class="empty">검색 결과가 없습니다.</div>';}
async function ranking(){content.innerHTML=heading('수호자 랭킹','이 서버에서 완료한 게임의 기록입니다. 모드별로 비교해보세요.','HALL OF GUARDIANS')+'<div class="filters"><select id="rank-mode"><option value="all">모든 모드</option><option value="single">싱글</option><option value="coop">협동</option><option value="versus">대전</option></select></div><div id="rank-list">기록을 불러오는 중…</div>';try{const list=await api('rankings');const render=()=>{const mode=$('#rank-mode').value,rows=list.filter(r=>mode==='all'||r.mode===mode);$('#rank-list').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>순위</th><th>수호자</th><th>모드</th><th>라운드</th><th>처치</th><th>시간</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${String(i+1).padStart(2,'0')}</td><td>${esc(r.name)}</td><td>${modeNames[r.mode]} / ${r.random?'랜덤':'클래식'} / ${r.hard?'하드 '+r.hard:'일반'}</td><td>${r.round}</td><td>${r.kills}</td><td>${Math.floor(r.seconds/60)}:${String(r.seconds%60).padStart(2,'0')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">아직 완료된 게임이 없습니다. 첫 기록에 도전하세요.</div>';};if($('#rank-mode')){$('#rank-mode').onchange=render;render();}}catch(e){toast(e.message);}}
function guide(){content.innerHTML=heading('방어선 운용 가이드','소환부터 마지막 웨이브까지, 수호자가 알아야 할 것들.','FIELD MANUAL')+`<div class="guide-grid"><article><h3>01 / 전투와 이동</h3><p>60골드로 시작합니다. 챔피언을 30골드에 소환하고 궤도 가까이에 배치하세요. 챔피언 클릭 후 맵을 우클릭하거나 키보드 방향키로 이동합니다. 터치 화면은 챔피언 선택 후 빈 안쪽 영역을 누릅니다. 사거리 안의 적은 자동 공격합니다. 소환된 챔피언은 길 안쪽에 배치됩니다. 자동 배치로 진형을 정리하거나 챔피언별 공격 우선순위를 바꿀 수 있습니다. 면역인 적보다 피해를 줄 수 있는 적을 우선 공격합니다.<br>적은 네모 길을 시계 방향으로 계속 순환합니다. 매 라운드 30마리, 10라운드마다 마지막 1마리가 보스입니다. 살아 있는 적이 100마리 쌓이면 패배합니다.</p></article><article><h3>02 / 함께하거나 경쟁하거나</h3><p>싱글·협동은 적을 전부 처치하거나 60초가 지나면 다음 라운드가 시작됩니다. 남은 적은 사라지지 않으며 100마리가 쌓이면 패배합니다. 싱글은 일시정지와 1~3배속을 지원하며, 배속에 따라 게임 안의 60초도 빨라집니다. 협동은 한 변이 1.4배 큰 전장을 공유합니다. 일반 적은 모두에게 1골드, 보스는 모두에게 30골드를 지급합니다.<br>대전은 각자의 맵에서 싸웁니다. 누군가 해당 라운드를 모두 끝내면 다른 플레이어에게도 다음 웨이브가 추가됩니다. 마지막 생존자가 승리합니다.</p></article><article><h3>03 / 조합과 성장</h3><p>동일한 이름과 등급 2개를 합성하면 확정적으로 상위 등급 1개가 됩니다. 레전더리는 합성할 수 없습니다. 소모되는 챔피언의 장비는 가방으로 돌아옵니다.<br>무기·장갑·신발·목걸이를 각각 1개씩 장착할 수 있습니다. 장비 선택 후 장착할 챔피언을 선택하세요. 이미 장착한 부위는 교체되며 기존 장비는 반환됩니다.</p></article><article><h3>04 / 속성과 하드 모드</h3><p>일치하는 방어속성은 피해를 65% 감소시킵니다. 관통과 방깎으로 감소율을 낮출 수 있습니다. 물리면역·마법면역은 해당 계열 피해를 완전히 막습니다. 독은 별도 계열입니다.<br>하드 I~V는 단계당 체력 +50%, 속도 +5%, 추가 방어속성을 부여합니다. 물리와 마법 완전면역은 동시에 붙지 않습니다. 한 계열에 치우치지 않은 조합이 중요합니다.</p></article><article><h3>05 / 소환 확률</h3><p>챔피언·장비는 각각 독립된 상점 레벨을 가집니다. 강화 비용은 현재 레벨 × 40골드입니다. 최대 레벨은 10이며, 레벨에 따라 확률이 선형 조정됩니다.</p><table><thead><tr><th>등급</th><th>Lv.1</th><th>Lv.10</th></tr></thead><tbody>${TIERS.map((t,i)=>`<tr><td style="color:${COLORS[i]}">${t}</td><td>${chances(1)[i]}%</td><td>${chances(10)[i]}%</td></tr>`).join('')}</tbody></table></article><article><h3>06 / 온라인 접속</h3><p>협동과 대전은 같은 서버에 접속한 2명 또는 4명이 필요합니다. 대기실을 만들고 다른 플레이어가 입장하면 방장이 준비 화면으로 전환합니다. 각자 소환을 마친 뒤 방장이 전투를 시작합니다.<br>전투 중 페이지를 새로고침하면 현재 방에 다시 연결됩니다. 플레이어가 방을 나가면 해당 게임은 종료됩니다. 연결만 끊어진 동안에는 서버 전투가 계속됩니다.</p></article></div>`;}
function battle(){arenaRenderer.previous=null;arenaRenderer.current=null;selectedEnemy=null;window.scrollTo(0,0);page='play';viewBoard=Math.max(0,game.mode==='versus'?game.players.findIndex(p=>p.id===user.id):0);content.innerHTML=`<div id="result"></div><div class="battle-top"><div><span class="eyebrow">${modeNames[game.mode].toUpperCase()} · ${game.random?'RANDOM':'CLASSIC'}</span><div class="round-number" id="round"></div></div><div><span id="wave-status" class="wave-status"></span><button class="small-btn" id="leave">나가기 ↗</button></div></div><div id="board-tabs" class="board-tabs"></div><div class="battle-layout"><div><div class="arena-wrap"><canvas id="arena" width="800" height="800" aria-label="전투 맵. 챔피언을 클릭하여 선택 후 우클릭 또는 방향키로 이동합니다."></canvas><div class="arena-caption">SELECT CHAMPION → RIGHT CLICK TO MOVE / ARROW KEYS</div></div><div class="panel" style="margin-top:14px"><h3>보유 챔피언 <span id="hero-count"></span></h3><div class="inventory" id="heroes"></div></div><div class="panel" style="margin-top:12px"><h3>장비 가방 · 선택 후 챔피언에 장착</h3><div class="inventory" id="items"></div></div></div><aside class="battle-side"><section class="panel"><h3>수호자 현황 <span style="float:right;color:#7c8f9a;font-size:9px">처치 수</span></h3><div id="scores"></div></section><section class="panel"><div class="gold" id="gold"></div><div class="draw-row"><button data-draw="hero">♜ 챔피언 소환<small>30 G</small></button><button data-draw="item">◇ 장비 뽑기<small>30 G</small></button></div><div id="upgrades"></div><div id="probabilities" class="probabilities"></div><button class="primary" id="start">전투 시작 <span>→</span></button></section><section class="panel" id="detail"></section><section class="panel"><h3>전장 브리핑</h3><div class="muted" id="briefing"></div></section></aside></div>`;installBattleTools(game);const cv=$('#arena');installDragSelect(cv);cv.addEventListener('contextmenu',e=>{e.preventDefault();moveAt(e);});cv.addEventListener('click',e=>{const pos=canvasPos(e),owners=game.mode==='versus'?[game.players[viewBoard]]:game.players;let hit=null;for(const p of owners)for(const c of p.champions)if(Math.hypot((arenaRenderer.positions.get(c.id)||c).x-pos.x,(arenaRenderer.positions.get(c.id)||c).y-pos.y)<40)hit=c;if(hit){selected=hit.id;selectedItem=null;}else if(selected&&pos.x>=140&&pos.x<=660&&pos.y>=140&&pos.y<=660)moveAt(e);else{const m=game.boards[viewBoard].monsters.find(m=>Math.hypot((arenaRenderer.positions.get(m.id)||position(m.p)).x-pos.x,(arenaRenderer.positions.get(m.id)||position(m.p)).y-pos.y)<(m.boss?30:22));if(m){selectedEnemy=m.id;}if(m)toast(`${m.boss?'보스':'몬스터'} · HP ${Math.ceil(m.hp)} / ${Math.ceil(m.maxHp)} · ${m.defenses.join(', ')}`);}updateBattle();});}
function canvasPos(e){const rect=$('#arena').getBoundingClientRect();return {x:(e.clientX-rect.left)/rect.width*800,y:(e.clientY-rect.top)/rect.height*800};}
function moveAt(e){if(!selected&&!selectedIds.length)return;const pos=canvasPos(e);const ids=selectedIds.length?selectedIds:[selected];act({type:'moveGroup',ids,x:pos.x,y:pos.y});}
function installDragSelect(cv){
  cv.addEventListener('pointerdown',e=>{if(e.button!==0)return;const p=canvasPos(e);dragStart=p;dragNow=p;cv.setPointerCapture?.(e.pointerId);});
  cv.addEventListener('pointermove',e=>{if(!dragStart)return;dragNow=canvasPos(e);});
  cv.addEventListener('pointerup',e=>{if(!dragStart)return;const end=canvasPos(e),dx=end.x-dragStart.x,dy=end.y-dragStart.y;if(Math.hypot(dx,dy)>12){const x1=Math.min(dragStart.x,end.x),x2=Math.max(dragStart.x,end.x),y1=Math.min(dragStart.y,end.y),y2=Math.max(dragStart.y,end.y);selectedIds=me().champions.filter(c=>{const p=arenaRenderer.positions.get(c.id)||c;return p.x>=x1&&p.x<=x2&&p.y>=y1&&p.y<=y2;}).map(c=>c.id);selected=selectedIds[0]||null;selectedItem=null;if(selectedIds.length)toast(selectedIds.length+'명 선택됨 · 우클릭으로 함께 이동');updateBattle();}dragStart=null;dragNow=null;});
}
function updateBattle(){if(!game||!$('#arena'))return;updateCombat(game,room,user,selected,selectedItem,viewBoard,connected,abilities,effects,selectedEnemy);}
function drawArena(){arenaRenderer.draw($('#arena'),viewBoard,selected,selectedEnemy);requestAnimationFrame(drawArena);}
async function leave(){try{await api('leave',{});events?.close();events=null;room=null;game=null;selected=null;selectedItem=null;home();}catch(e){toast(e.message);}}
document.addEventListener('click',async e=>{const el=e.target.closest('button');if(!el)return;try{if(el.dataset.preview!==undefined){openAnimationPreview(Number(el.dataset.preview),Number(el.dataset.previewTier??catalogTier));return;}if(el.dataset.page){window.scrollTo(0,0);if(room){toast('현재 방에서 나간 뒤 다른 메뉴를 이용하세요.');return;}page=el.dataset.page;document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n===el));$('#page-title').textContent=el.querySelector('span').textContent;filter='';filterType='all';if(page==='play')home();else if(page==='ranking')ranking();else if(page==='guide')guide();else catalog(page);}if(el.dataset.mode){options.mode=el.dataset.mode;home();}if(el.dataset.random){options.random=el.dataset.random==='true';home();}if(el.dataset.capacity){options.capacity=Number(el.dataset.capacity);home();}if(el.id==='deploy'){if(!user){$('#login').showModal();return;}el.disabled=true;await api('rooms',options);subscribe();}if(el.dataset.join){await api('join',{id:el.dataset.join});subscribe();}if(el.id==='refresh-rooms')loadRooms();if(el.id==='leave'||el.id==='return-home')leave();if(el.id==='login-open'){if(room){toast('계정을 변경하려면 현재 방에서 나가세요.');return;}$('#login').showModal();}if(el.id==='login-close')$('#login').close();if(el.dataset.action)act({type:el.dataset.action});if(el.id==='pause-game')act({type:'pause'});if(el.dataset.speed)act({type:'speed',value:Number(el.dataset.speed)});if(el.id==='formation')act({type:'formation'});if(el.id==='start')act({type:'start'});if(el.dataset.draw)act({type:'draw',kind:el.dataset.draw});if(el.dataset.upgrade)act({type:'upgrade',kind:el.dataset.upgrade});if(el.dataset.select){selected=Number(el.dataset.select);selectedItem=null;updateBattle();}if(el.dataset.item){selectedItem=Number(el.dataset.item);updateBattle();}if(el.dataset.merge)act({type:'merge',kind:el.dataset.merge,id:Number(el.dataset.id)});if(el.id==='equip'){await act({type:'equip',id:Number($('#equip-target').value),item:selectedItem});selectedItem=null;}if(el.dataset.unequip)act({type:'unequip',id:selected,slot:Number(el.dataset.unequip)});if(el.dataset.board){viewBoard=Number(el.dataset.board);updateBattle();}}catch(err){el.disabled=false;toast(err.message);}});
document.addEventListener('change',e=>{if(e.target.id==='target-priority')act({type:'target',id:selected,value:e.target.value});if(['hero-merge-only','item-merge-only','item-slot-filter'].includes(e.target.id))updateBattle();if(e.target.id==='difficulty'){options.hard=Number(e.target.value);home();}if(e.target.id==='filter-type'){filterType=e.target.value;catalogGrid(page);}if(e.target.id==='catalog-tier'){catalogTier=Number(e.target.value);catalogGrid(page);}});
document.addEventListener('input',e=>{if(e.target.id==='hero-search')updateBattle();if(e.target.id==='search'){filter=e.target.value;catalogGrid(page);}});
let lastKey=0;document.addEventListener('keydown',e=>{if(!game||['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName))return;if(e.code==='Space'&&game.mode==='single'){e.preventDefault();if(!e.repeat)act({type:'pause'});return;}if(!selected)return;const directions={ArrowLeft:[-30,0],ArrowRight:[30,0],ArrowUp:[0,-30],ArrowDown:[0,30]};if(directions[e.key]){e.preventDefault();if(Date.now()-lastKey<80)return;lastKey=Date.now();const c=me().champions.find(c=>c.id===selected);if(c){const pos=c.destination||c;act({type:'move',id:selected,x:pos.x+directions[e.key][0],y:pos.y+directions[e.key][1]});}}});
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();try{const data=await api('login',{name:$('#nickname').value});setUser(data.user);$('#login').close();toast('대기실에 오신 것을 환영합니다.');if(page==='play')home();}catch(e){toast(e.message);}});
async function init(){home();try{const [session,config]=await Promise.all([api('me'),api('config')]);setUser(session.user);connected=true;$('.live').innerHTML='<b></b> 방어 서버 온라인';if(config.clientId){$('#google-note').textContent='Google 계정으로 수호자 프로필을 연결합니다.';const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.onload=()=>{google.accounts.id.initialize({client_id:config.clientId,callback:async response=>{try{const data=await api('login',{credential:response.credential});setUser(data.user);$('#login').close();home();}catch(e){toast(e.message);}}});google.accounts.id.renderButton($('#google-login'),{theme:'outline',size:'large',width:330});};script.onerror=()=>$('#google-note').textContent='Google 로그인 스크립트를 불러올 수 없습니다.';document.head.append(script);}else $('#google-note').textContent='Google 로그인은 서버에 GOOGLE_CLIENT_ID를 설정하면 활성화됩니다.';if(session.room)subscribe();}catch(e){$('.live').textContent='서버에 연결할 수 없습니다';toast(e.message);}}
init();drawArena();
