import {renderSynergies} from './synergies.js';
import {lobbyMarkup,updateLobbyChat,openLobbyCards} from './lobby.js';
import {boardOwners} from './engine.js';
import {BattleAnnouncements} from './battle-announcements.js';
const battleAnnouncements=new BattleAnnouncements();
import {renderTalents} from './talents.js';
import {catalogShell,catalogCards,rankingShell,renderRanks,enhanceGuide} from './command-ui.js';
import { portraitMarkup, CHARACTER_ATLAS } from './art.js';
import { installBattleTools, updateCombat, announceWave } from './battle-ui.js';
import { ArenaRenderer } from './renderer.js';
const arenaRenderer = new ArenaRenderer();
let selectedEnemy = null;
import {TIERS,COLORS,TYPES,CHAMPIONS,ITEMS,SLOTS,chances,stats,position} from './engine.js';
const $=s=>document.querySelector(s),content=$('#content'),icons=['⌖','➶','⚔','❄','♨','◆','≋','☣','✹','✦'];
const modeNames={single:'싱글 디펜스',coop:'협동 디펜스',versus:'대전 디펜스'};
const abilities=['긴 사거리의 강력한 단발 공격','빠른 공격속도와 안정적인 화력','짧은 사거리, 묵직한 근접 피해','적 둔화 · 유니크 이상 빙결','강력한 화염 · 유니크 이상 범위 공격','적 기절 · 유니크 이상 범위 기절','빠른 연사 · 유니크 이상 주변 공속 +25%','중첩되지 않는 지속 독 피해','유니크 이상 범위 폭발 및 추가 피해','강한 아군에게 10초마다 피해량 또는 공격속도 +30~60% 버프',"최대 3대상 번개 공격 · 유니크 이상 5대상 및 짧은 기절","치명타 30%, 배율 ×2.2 · 유니크 이상 체력 35% 이하 적 피해 +50%","물리 관통 20% · 2대상 창술 · 유니크 이상 적 저항 감소","2대상 수속성 둔화 · 유니크 이상 4대상 공격","사거리 410, 물리 관통 25% · 유니크 이상 보스 피해 +75%"];
const effects=['공격력 증가','공격속도 증가','사거리 증가','치명타 확률 증가','치명타 배율 증가','물리 방어관통','마법 방어관통','연쇄 공격','둔화 부여','방어 저항 감소'];
let user=null,page='play',options={mode:'single',random:false,hard:0,capacity:2},room=null,game=null,events=null,selected=null,selectedIds=[],selectedItem=null,viewBoard=0,toastTimer,filter='',filterType='all',catalogTier=0,connected=false,dragStart=null,dragNow=null;
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
async function api(path,body){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'서버 요청 실패');return data;}
function me(){return game?.players.find(p=>p.id===user?.id);}
async function act(a){try{await api('action',a);return true;}catch(e){toast(e.message);return false;}}
function setUser(u){user=u;$('#user-name').textContent=u?.name||'로그인 전';$('#account-kind').textContent=u?(u.google?'Google 계정 연결됨':'로그인이 필요합니다'):'로그인이 필요합니다';$('#login-open').textContent=u?'계정 변경 ↗':'계정 연결 ↗';}
function heading(title,sub,label='PLAY YOUR STRATEGY'){return `<div class="page-heading"><div><span class="eyebrow">${label}</span><h1>${title}</h1><p>${sub}</p></div><span class="season">SEASON 00 · THE FIRST LOOP</span></div>`;}
function home(){document.body.classList.remove("shop-mode");document.body.classList.remove("lobby-mode");battleAnnouncements.clear();content.classList.remove('manual-page');document.body.classList.remove("battle-mode");window.scrollTo(0,0);content.innerHTML=`<section class="hero"><div class="hero-copy"><span class="badge">PLAY YOUR STRATEGY</span><h2>끝없는 웨이브,<br><em>당신의 방어선.</em></h2><p>같은 길을 도는 적들, 매번 달라지는 전략.<br>당신만의 챔피언 조합으로 마지막 웨이브까지.</p><div class="hero-tags"><span>◈ 100개의 라운드</span><span>♜ ${CHAMPIONS.length}종의 챔피언</span><span>◇ 7단계의 등급</span></div></div><canvas class="hero-art" id="hero-canvas" width="650" height="400" aria-label="생성 이미지로 만든 판타지 챔피언들"></canvas></section><div class="section-head"><h2>플레이 모드</h2><span>함께할 방식을 선택하세요</span><span class="right">01 — SELECT MODE</span></div><div class="modes">${['single','coop','versus'].map((m,i)=>`<button data-mode="${m}" class="mode-card ${options.mode===m?'selected':''}"><span class="check">${options.mode===m?'●':'○'}</span><span class="mode-icon">${['♜','♜♜','⚔'][i]}</span><h3>${modeNames[m]}</h3><span class="count">${i?'2 / 3 / 4 PLAYERS':'SOLO'}</span><p>${['나만의 속도로 완성하는 전략.<br>전멸 즉시, 또는 60초마다 다음 웨이브.','각자의 전장, 함께 지키는 한도.<br>몬스터 100마리 공유 · 월드보스 협공 · 골드 지원.','상대보다 빠르게, 끝까지 살아남기.<br>먼저 끝낸 라운드가 모두의 다음 웨이브로.'][i]}</p></button>`).join('')}</div><div class="setup"><section class="settings"><div class="settings-row"><div><label>몬스터 출현 규칙</label><small>클래식은 고정, 랜덤은 매번 새로운 적</small></div><div class="segments"><button data-random="false" class="${!options.random?'selected':''}">클래식</button><button data-random="true" class="${options.random?'selected':''}">랜덤</button></div></div><div class="settings-row"><div><label>도전 난이도</label><small>하드 단계마다 체력과 방어속성 증가</small></div><select id="difficulty" aria-label="난이도">${['일반 모드','하드 I','하드 II','하드 III','하드 IV','하드 V'].map((s,i)=>`<option value="${i}" ${options.hard===i?'selected':''}>${s}</option>`).join('')}</select></div>${options.mode!=='single'?`<div class="settings-row"><label>플레이어 수</label><div class="segments"><button data-capacity="2" class="${options.capacity===2?'selected':''}">2인</button><button data-capacity="3" class="${options.capacity===3?'selected':''}">3인</button><button data-capacity="4" class="${options.capacity===4?'selected':''}">4인</button></div></div>`:''}</section><section class="deploy"><div><span class="label">READY TO DEPLOY</span><h3>${modeNames[options.mode]}</h3><p>${options.random?'랜덤':'클래식'} · ${options.hard?'하드 '+options.hard+'단계':'일반 모드'} · 시작 골드 60 G</p></div><button class="primary" id="deploy">${options.mode==='single'?'전투 준비':'대기실 만들기'}<span>→</span></button></section></div><div class="footer-notes"><span>↻ 라운드당 30마리 출현</span><span>⚑ 60초마다 웨이브 · 100마리 누적 패배</span><span>⌁ 소환 · 장비 뽑기 30 G</span></div>${options.mode!=='single'?'<div class="section-head"><h2>공개 대기실</h2><button class="mini-btn right" id="refresh-rooms">새로고침 ↻</button></div><div id="rooms" class="room-list"></div>':''}`;if(options.mode!=='single')loadRooms();}
function drawHero(){const cv=$('#hero-canvas');if(!cv)return;const ctx=cv.getContext('2d');ctx.clearRect(0,0,650,400);ctx.save();ctx.translate(325,198);ctx.scale(1,.58);ctx.rotate(-Math.PI/4);ctx.fillStyle='#0d151a';ctx.shadowColor='#a4ff6030';ctx.shadowBlur=45;ctx.fillRect(-160,-160,320,320);ctx.shadowBlur=0;ctx.lineWidth=35;ctx.strokeStyle='#2c3d38';ctx.strokeRect(-168,-168,336,336);ctx.lineWidth=1;ctx.strokeStyle='#72905e';ctx.strokeRect(-189,-189,378,378);ctx.strokeStyle='#627c543f';for(let i=-140;i<=140;i+=35){ctx.beginPath();ctx.moveTo(i,-145);ctx.lineTo(i,145);ctx.stroke();ctx.beginPath();ctx.moveTo(-145,i);ctx.lineTo(145,i);ctx.stroke();}for(let i=0;i<22;i++){let a=i/22*4,x,y;if(a<1){x=-168+336*a;y=-168;}else if(a<2){x=168;y=-168+336*(a-1);}else if(a<3){x=168-336*(a-2);y=168;}else{x=-168;y=168-336*(a-3);}ctx.fillStyle=i%6===0?'#d5b78a':'#89917c';ctx.fillRect(x-7,y-7,14,14);}for(const [x,y,col]of [[-60,-55,'#b9f66d'],[80,0,'#73cccb'],[-30,90,'#bb9aff']]){ctx.fillStyle=col+'18';ctx.beginPath();ctx.arc(x,y,70,0,Math.PI*2);ctx.fill();ctx.strokeStyle=col+'55';ctx.stroke();ctx.fillStyle=col;ctx.shadowColor=col;ctx.shadowBlur=18;ctx.fillRect(x-14,y-14,28,28);ctx.shadowBlur=0;ctx.strokeStyle=col;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(168,y);ctx.stroke();}ctx.restore();ctx.fillStyle='#bad09a';ctx.font='10px monospace';ctx.fillText('SECTOR 01 / SQUARE LOOP',325,369);const art=new Image();art.onload=()=>{if(!cv.isConnected)return;ctx.clearRect(0,0,650,400);ctx.drawImage(art,art.width*2/5,0,art.width*3/5,art.height/2,0,0,650,400);const shade=ctx.createLinearGradient(0,0,200,0);shade.addColorStop(0,'#172221');shade.addColorStop(1,'#17222100');ctx.fillStyle=shade;ctx.fillRect(0,0,650,400);};art.src=CHARACTER_ATLAS;}
async function loadRooms(){try{if(!user){$('#rooms').innerHTML='<div class="empty">로그인 후 대기실에 입장할 수 있습니다.</div>';return;}const list=await api('rooms');if(!$('#rooms'))return;$('#rooms').innerHTML=list.length?list.map(r=>`<div class="room-row"><span>◈</span><div><strong>${esc(r.name)}</strong><p class="muted" style="margin:5px 0 0">${modeNames[r.mode]} · ${r.random?'랜덤':'클래식'} · ${r.hard?'하드 '+r.hard:'일반'} · ${r.players.length}/${r.capacity}인</p></div><button data-join="${r.id}" ${r.status!=='waiting'||r.players.length>=r.capacity?'disabled':''}>${r.status==='waiting'?'입장하기 →':'게임 진행 중'}</button></div>`).join(''):'<div class="empty">아직 열린 대기실이 없습니다. 첫 번째 방을 만들어보세요.</div>';}catch(e){toast(e.message);}}
function subscribe(){events?.close();events=new EventSource('/api/events');events.onmessage=e=>{connected=true;const data=JSON.parse(e.data),wasGame=!!game;room=data.room;const previousRound=game?.round||0;game=data.game;if(game){if(!wasGame||!$('#arena'))battle();arenaRenderer.receive(game);updateBattle();battleAnnouncements.update(game,room.id,user.id);}else {battleAnnouncements.update(null,room.id,user.id);waiting();}};events.onerror=()=>{connected=false;updateBattle();toast('서버 연결이 끊겼습니다. 자동으로 재연결합니다.');};}
function waiting(){if(!document.body.classList.contains('lobby-mode'))window.scrollTo(0,0);document.body.classList.remove('battle-mode');document.body.classList.add('lobby-mode');const key=JSON.stringify([room.id,room.host,room.mode,room.capacity,room.random,room.hard,room.players]);if(content.dataset.lobbyKey!==key||!document.querySelector('.lobby-screen')){const input=document.querySelector('#lobby-chat-input'),draft=input?.value||'',focused=document.activeElement===input;content.innerHTML=lobbyMarkup(room,user);content.dataset.lobbyKey=key;const next=document.querySelector('#lobby-chat-input');next.value=draft;if(focused)next.focus();}updateLobbyChat(room.messages);}
function catalog(kind){content.classList.remove('manual-page');content.innerHTML=catalogShell(kind,filter,filterType,catalogTier);catalogGrid(kind);}
function catalogGrid(kind){catalogCards(kind,filter,filterType,catalogTier);}
async function ranking(){content.classList.remove('manual-page');content.innerHTML=rankingShell();try{const list=await api('rankings');renderRanks(list,user,modeNames);}catch(e){toast(e.message);}}
function guide(){content.innerHTML=heading('방어선 운용 가이드','소환부터 마지막 웨이브까지, 수호자가 알아야 할 것들.','FIELD MANUAL')+`<div class="guide-grid"><article><h3>01 / 전투와 이동</h3><p>60골드로 시작합니다. 챔피언을 30골드에 소환하고 궤도 가까이에 배치하세요. 챔피언 클릭 후 맵을 우클릭하거나 키보드 방향키로 이동합니다. 터치 화면은 챔피언 선택 후 빈 안쪽 영역을 누릅니다. 사거리 안의 적은 자동 공격하며, 밖에 있으면 피해를 줄 수 있는 적에게 자동 접근합니다. 챔피언 정보에서 자동 접근을 끄면 제자리 방어를 합니다. 이동 중에는 공격하지 않으며 챔피언끼리 겹칠 수 없습니다. 소환된 챔피언은 길 안쪽에 배치됩니다. 자동 배치로 진형을 정리하거나 챔피언별 공격 우선순위를 바꿀 수 있습니다. 저항이 낮아 피해를 더 줄 수 있는 적을 우선 공격합니다.<br>적은 네모 길을 시계 방향으로 계속 순환합니다. 매 라운드 30마리, 싱글·대전은 5라운드마다 마지막 1마리가 보스입니다. 살아 있는 적이 100마리 쌓이면 패배합니다.</p></article><article><h3>02 / 함께하거나 경쟁하거나</h3><p>싱글·협동은 적을 전부 처치하거나 60초가 지나면 다음 라운드가 시작됩니다. 남은 적은 사라지지 않으며 100마리가 쌓이면 패배합니다. 싱글은 일시정지를 지원하며 모든 모드는 2배속 고정으로, 배속에 따라 게임 안의 60초도 빨라집니다. 협동은 각자 전장과 골드를 가집니다. 전체 전장의 살아 있는 몬스터 합계가 100마리면 공동 패배합니다. 5라운드마다 별도 전장에 월드보스가 등장하며 챔피언을 파견해 다음 월드보스가 등장하는 라운드 전까지 처치해야 합니다. 월드보스 탭으로 실시간 전투를 확인하고 아군에게 10골드씩 지원할 수 있습니다.<br>대전은 각자의 맵에서 싸웁니다. 누군가 해당 라운드를 모두 끝내면 다른 플레이어에게도 다음 웨이브가 추가됩니다. 마지막 생존자가 승리합니다.</p></article><article><h3>03 / 조합과 성장</h3><p>맵 우측 상단에서 내 챔피언의 최근 5초 DPS를 확인할 수 있습니다. 축복술사는 직접 공격하지 않고, 강한 아군에게 10초마다 피해량 또는 공격속도 +30~60% 버프를 부여합니다.<br>동일한 이름과 등급 2개를 합성하면 확정적으로 상위 등급 1개가 됩니다. 레전더리는 합성할 수 없습니다. 소모되는 챔피언의 장비는 가방으로 돌아옵니다.<br>무기·장갑·신발·목걸이를 각각 1개씩 장착할 수 있습니다. 장비 선택 후 장착할 챔피언을 선택하세요. 이미 장착한 부위는 교체되며 기존 장비는 반환됩니다.</p></article><article><h3>04 / 속성과 하드 모드</h3><p>일치하는 방어속성은 피해를 65% 감소시킵니다. 관통과 방깎으로 감소율을 낮출 수 있습니다. 물리저항·마법저항은 해당 계열 피해를 65% 감소시킵니다. 독은 별도 계열입니다.<br>하드 I~V는 단계당 체력 +50%, 속도 +5%, 추가 방어속성을 부여합니다. 보스 체력은 일반 적의 60배입니다. 30초마다 공포(5초 공격 금지), 공격속도 50% 감소(10초), 몬스터 체력 20% 회복, 이동속도 50% 증가(10초), 피해 50% 감소 보호막(10초)과 서리 폭풍·암흑 장막·마력 봉인을 순환 사용합니다. 한 계열에 치우치지 않은 조합이 중요합니다.</p></article><article><h3>05 / 소환 확률</h3><p>챔피언·장비는 각각 독립된 상점 레벨을 가집니다. 강화 비용은 현재 레벨 × 35골드입니다. 최대 레벨은 10이며, 레벨에 따라 확률이 선형 조정됩니다.</p><table><thead><tr><th>등급</th><th>Lv.1</th><th>Lv.10</th></tr></thead><tbody>${TIERS.map((t,i)=>`<tr><td style="color:${COLORS[i]}">${t}</td><td>${chances(1)[i]}%</td><td>${chances(10)[i]}%</td></tr>`).join('')}</tbody></table></article><article><h3>06 / 온라인 접속</h3><p>협동과 대전은 같은 서버에 접속한 2명, 3명 또는 4명이 필요합니다. 대기실을 만들고 다른 플레이어가 입장하면 방장이 준비 화면으로 전환합니다. 각자 소환을 마친 뒤 방장이 전투를 시작합니다.<br>전투 중 페이지를 새로고침하면 현재 방에 다시 연결됩니다. 플레이어가 방을 나가면 해당 게임은 종료됩니다. 연결만 끊어진 동안에는 서버 전투가 계속됩니다.</p></article></div>`;enhanceGuide();}
function battle(){document.body.classList.remove("lobby-mode");arenaRenderer.previous=null;arenaRenderer.current=null;selectedEnemy=null;window.scrollTo(0,0);page='play';viewBoard=Math.max(0,game.mode!=='single'?game.players.findIndex(p=>p.id===user.id):0);content.innerHTML=`<div id="result"></div><div class="battle-top"><div><span class="eyebrow">${modeNames[game.mode].toUpperCase()} · ${game.random?'RANDOM':'CLASSIC'}</span><div class="round-number" id="round"></div></div><div><span id="wave-status" class="wave-status"></span><button class="small-btn" id="leave">나가기 ↗</button></div></div><div id="board-tabs" class="board-tabs"></div><div class="battle-layout"><div><div class="arena-wrap"><canvas id="arena" width="800" height="800" aria-label="전투 맵. 챔피언을 클릭하여 선택 후 우클릭으로 이동합니다."></canvas><div class="arena-caption">SELECT CHAMPION → RIGHT CLICK TO MOVE · 1–4 PLAYER MAP · 5 WORLD BOSS</div></div><div class="panel" style="margin-top:14px"><h3>보유 챔피언 <span id="hero-count"></span></h3><div class="inventory" id="heroes"></div></div><div class="panel" style="margin-top:12px"><h3>장비 가방 · 선택 후 챔피언에 장착</h3><div class="inventory" id="items"></div></div></div><aside class="battle-side"><section class="panel"><h3>수호자 현황 <span style="float:right;color:#7c8f9a;font-size:9px">처치 수</span></h3><div id="scores"></div></section><section class="panel"><div class="gold" id="gold"></div><div class="draw-row"><button data-draw="hero">♜ 챔피언 소환<small>30 G</small></button><button data-draw="item">◇ 장비 뽑기<small>30 G</small></button></div><div id="upgrades"></div><div id="probabilities" class="probabilities"></div><button class="primary" id="start">전투 시작 <span>→</span></button></section><section class="panel" id="detail"></section><section class="panel"><h3>전장 브리핑</h3><div class="muted" id="briefing"></div></section></aside></div>`;installBattleTools(game);const cv=$('#arena');installDragSelect(cv);cv.addEventListener('contextmenu',e=>{e.preventDefault();moveAt(e);});cv.addEventListener('click',e=>{const pos=canvasPos(e),owners=boardOwners(game,viewBoard);let hit=null;for(const p of owners)for(const c of p.champions)if(Math.hypot((arenaRenderer.positions.get(c.id)||c).x-pos.x,(arenaRenderer.positions.get(c.id)||c).y-pos.y)<40)hit=c;if(hit){selectedEnemy=null;selected=hit.id;selectedIds=[hit.id];selectedItem=null;}else if(game.boards[viewBoard].monsters.some(m=>Math.hypot(position(m.p,m).x-pos.x,position(m.p,m).y-pos.y)<(m.boss?40:30))){selectedEnemy=game.boards[viewBoard].monsters.find(m=>Math.hypot(position(m.p,m).x-pos.x,position(m.p,m).y-pos.y)<(m.boss?40:30)).id;}else{const m=game.boards[viewBoard].monsters.find(m=>Math.hypot((arenaRenderer.positions.get(m.id)||position(m.p,m)).x-pos.x,(arenaRenderer.positions.get(m.id)||position(m.p,m)).y-pos.y)<(m.boss?30:22));if(m){selectedEnemy=m.id;}if(m)toast(`${m.boss?'보스':'몬스터'} · HP ${Math.ceil(m.hp)} / ${Math.ceil(m.maxHp)} · ${m.defenses.join(', ')}`);}updateBattle();});}
function canvasPos(e){const rect=$('#arena').getBoundingClientRect();return {x:(e.clientX-rect.left)/rect.width*800,y:(e.clientY-rect.top)/rect.height*800};}
function moveAt(e){if(!selected&&!selectedIds.length)return;const pos=canvasPos(e);const ids=selectedIds.length?selectedIds:[selected];act({type:'moveGroup',ids,x:pos.x,y:pos.y});}
function installDragSelect(cv){
  cv.addEventListener('pointerdown',e=>{if(e.button!==0)return;const p=canvasPos(e);dragStart=p;dragNow=p;cv.setPointerCapture?.(e.pointerId);});
  cv.addEventListener('pointermove',e=>{if(!dragStart)return;dragNow=canvasPos(e);});
  cv.addEventListener('pointerup',e=>{if(!dragStart)return;const end=canvasPos(e),dx=end.x-dragStart.x,dy=end.y-dragStart.y;if(Math.hypot(dx,dy)>12){const x1=Math.min(dragStart.x,end.x),x2=Math.max(dragStart.x,end.x),y1=Math.min(dragStart.y,end.y),y2=Math.max(dragStart.y,end.y);selectedIds=me().champions.filter(c=>{const p=arenaRenderer.positions.get(c.id)||c;return p.x>=x1&&p.x<=x2&&p.y>=y1&&p.y<=y2;}).map(c=>c.id);selected=selectedIds[0]||null;selectedItem=null;if(selectedIds.length)toast(selectedIds.length+'명 선택됨 · 우클릭으로 함께 이동');updateBattle();}dragStart=null;dragNow=null;});
}
function updateBattle(){if(!game||!$('#arena'))return;if(!game.players.flatMap(p=>p.champions).some(c=>c.id===selected)&&me()?.champions.length){selected=me().champions[0].id;selectedIds=[selected];}updateCombat(game,room,user,selected,selectedItem,viewBoard,connected,abilities,effects,selectedEnemy);renderSynergies(game,me());renderTalents(game,me(),connected,(index,round)=>act({type:'talent',index,round}));}
function drawArena(){arenaRenderer.draw($('#arena'),viewBoard,selected,selectedEnemy,selectedIds,dragStart,dragNow);requestAnimationFrame(drawArena);}
async function leave(){try{await api('leave',{});events?.close();events=null;room=null;game=null;selected=null;selectedItem=null;home();}catch(e){toast(e.message);}}
document.addEventListener('click',async e=>{const el=e.target.closest('button');if(!el)return;try{if(el.dataset.shopToggle){$('#battle-shop').hidden=!$('#battle-shop').hidden;return;}if(el.dataset.page){document.body.classList.remove('shop-mode');window.scrollTo(0,0);if(room){toast('현재 방에서 나간 뒤 다른 메뉴를 이용하세요.');return;}page=el.dataset.page;document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n===el));$('#page-title').textContent=el.querySelector('span').textContent;filter='';filterType='all';if(page==='play')home();else if(page==='ranking')ranking();else if(page==='guide')guide();else if(page==='settings')settings();else if(page==='shop')shop();else catalog(page);}if(el.dataset.mode){options.mode=el.dataset.mode;home();}if(el.dataset.random){options.random=el.dataset.random==='true';home();}if(el.dataset.capacity){options.capacity=Number(el.dataset.capacity);home();}if(el.id==='deploy'){if(!user){$('#login').showModal();return;}if(user.needsNickname){$('#nickname-dialog').showModal();return;}el.disabled=true;await api('rooms',options);subscribe();}if(el.dataset.join){await api('join',{id:el.dataset.join});subscribe();}if(el.id==='refresh-rooms')loadRooms();if(el.id==='leave'||el.id==='return-home')leave();if(el.id==='login-open'){if(room){toast('계정을 변경하려면 현재 방에서 나가세요.');return;}$('#login').showModal();}if(el.id==='login-close')$('#login').close();if(el.dataset.action)act({type:el.dataset.action});if(el.id==='pause-game')act({type:'pause'});if(el.id==='formation')act({type:'formation'});if(el.id==='start')act({type:'start'});if(el.dataset.draw)act({type:'draw',kind:el.dataset.draw});if(el.dataset.upgrade)act({type:'upgrade',kind:el.dataset.upgrade});if(el.dataset.select){selectedEnemy=null;selected=Number(el.dataset.select);selectedIds=[selected];selectedItem=null;updateBattle();}if(el.dataset.item){selectedEnemy=null;selectedItem=Number(el.dataset.item);updateBattle();}if(el.dataset.sell){requestChampionSale([Number(el.dataset.sell)]);return;}if(el.dataset.dispatch){await act({type:'dispatch',id:Number(el.dataset.dispatch)});return;}if(el.dataset.donate){await act({type:'donate',to:el.dataset.donate,amount:10});return;}if(el.dataset.merge)act({type:'merge',kind:el.dataset.merge,id:Number(el.dataset.id)});if(el.id==='equip'){await act({type:'equip',id:Number($('#equip-target').value),item:selectedItem});selectedItem=null;}if(el.dataset.unequip)act({type:'unequip',id:selected,slot:Number(el.dataset.unequip)});if(el.dataset.board){viewBoard=Number(el.dataset.board);updateBattle();}}catch(err){el.disabled=false;toast(err.message);}});
document.addEventListener('dragstart',e=>{const item=e.target.closest('[data-item]');if(!item)return;e.dataTransfer.setData('text/plain',item.dataset.item);e.dataTransfer.effectAllowed='move';item.classList.add('dragging');});
document.addEventListener('dragend',e=>e.target.closest('[data-item]')?.classList.remove('dragging'));
document.addEventListener('dragover',e=>{const hero=e.target.closest('[data-select]');if(!hero)return;e.preventDefault();e.dataTransfer.dropEffect='move';hero.classList.add('equip-drop');});
document.addEventListener('dragleave',e=>e.target.closest('[data-select]')?.classList.remove('equip-drop'));
document.addEventListener('drop',async e=>{const hero=e.target.closest('[data-select]');if(!hero)return;e.preventDefault();hero.classList.remove('equip-drop');const item=Number(e.dataTransfer.getData('text/plain'));if(!item)return;const ok=await act({type:'equip',id:Number(hero.dataset.select),item});if(ok){selected=Number(hero.dataset.select);selectedIds=[selected];selectedItem=null;toast('장비를 장착했습니다.');updateBattle();}});
document.addEventListener('change',e=>{if(e.target.id==='auto-approach')act({type:'autoApproach',id:selected,enabled:e.target.checked});if(e.target.id==='target-priority')act({type:'target',id:selected,value:e.target.value});if(['hero-merge-only','item-merge-only','item-slot-filter'].includes(e.target.id))updateBattle();if(e.target.id==='difficulty'){options.hard=Number(e.target.value);home();}if(e.target.id==='filter-type'){filterType=e.target.value;catalogGrid(page);}if(e.target.id==='catalog-tier'){catalogTier=Number(e.target.value);catalogGrid(page);}});
document.addEventListener('input',e=>{if(e.target.id==='hero-search')updateBattle();if(e.target.id==='search'){filter=e.target.value;catalogGrid(page);}});
let lastKey=0;document.addEventListener('keydown',e=>{if(!game||!$('#arena')||document.querySelector('dialog[open]')||e.target.isContentEditable||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||e.ctrlKey||e.altKey||e.metaKey)return;
const mapKey=/^(?:Digit|Numpad)([1-5])$/.exec(e.code);if(mapKey){e.preventDefault();if(e.repeat)return;const key=Number(mapKey[1]);const next=key===5?(game.mode==='coop'?game.players.length:-1):key-1;if(next<0||next>=game.boards.length||(key<5&&next>=game.players.length))return;viewBoard=next;selectedEnemy=null;dragStart=null;dragNow=null;updateBattle();return;}
if(['KeyS','KeyM','KeyX'].includes(e.code)){e.preventDefault();if(e.repeat||!connected||!['ready','playing','paused'].includes(game.status))return;const ids=[...new Set(selectedIds.length?selectedIds:[selected])].filter(id=>me()?.champions.some(c=>c.id===id));if(!ids.length)return;if(e.code==='KeyX')requestChampionSale(ids);else act({type:'autoApproach',ids,enabled:e.code==='KeyM'}).then(ok=>{if(ok)toast(ids.length+'명 · '+(e.code==='KeyS'?'제자리 방어':'자동 접근'));});return;}
if(e.target.tagName==='BUTTON')return;if(e.code==='Space'&&game.mode==='single'){e.preventDefault();if(!e.repeat)act({type:'pause'});return;}});
$('#login-form').addEventListener('submit',e=>e.preventDefault());
async function init(){home();try{const [session,config]=await Promise.all([api('me'),api('config')]);setUser(session.user);connected=true;$('.live').innerHTML='<b></b> 방어 서버 온라인';if(config.clientId){$('#google-note').textContent='Google 계정으로 수호자 프로필을 연결합니다.';const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.onload=()=>{google.accounts.id.initialize({client_id:config.clientId,callback:async response=>{try{const data=await api('login',{credential:response.credential});setUser(data.user);$('#login').close();home();if(user.needsNickname)$('#nickname-dialog').showModal();}catch(e){toast(e.message);}}});google.accounts.id.renderButton($('#google-login'),{theme:'outline',size:'large',width:330});};script.onerror=()=>$('#google-note').textContent='Google 로그인 스크립트를 불러올 수 없습니다.';document.head.append(script);}else $('#google-note').textContent='Google 로그인이 아직 설정되지 않았습니다. 서버에 GOOGLE_CLIENT_ID를 설정해야 플레이할 수 있습니다.';if(session.room)subscribe();else if(user?.needsNickname)$('#nickname-dialog').showModal();else if(!user)$('#login').showModal();}catch(e){$('.live').textContent='서버에 연결할 수 없습니다';toast(e.message);}}
init();drawArena();

function settings(){content.classList.remove('manual-page');content.innerHTML=`<section class="display-settings"><span class="eyebrow">SYSTEM SETTINGS</span><h1>설정</h1><p>모든 게임 화면에 동일한 해상도를 적용합니다.</p><div class="panel"><h2>화면 설정</h2><label><input type="checkbox" id="boss-sound" ${globalThis.loopBossMuted?'':'checked'}> 보스 효과음</label><br><label for="resolution">해상도</label><select id="resolution" aria-label="해상도"><option selected value="1920x1080">1920 × 1080 (16:9) · 고정</option></select><p>홈 · 도감 · 랭킹 · 전투 화면 모두 1920 × 1080으로 고정됩니다.</p><p class="muted">창 크기를 바꾸면 전체 화면을 같은 비율로 맞춥니다. 남는 공간은 검은 여백으로 표시하며, 화면 배치는 바뀌지 않습니다.</p><strong class="resolution-applied">✓ 적용 중 · 자동 저장</strong></div></section>`; }

document.addEventListener('click',async e=>{const el=e.target.closest('button');if(!el)return;try{if(el.id==='my-lobby-screen'){openLobbyCards(room.players.find(p=>p.id===user.id)?.lobbyCard??0,async card=>{await api('lobby-card',{card});toast('대기화면을 변경했습니다.');});}if(el.id==='copy-room'){await navigator.clipboard.writeText(room.id);toast('방 코드가 복사되었습니다.');}if(el.dataset.lobbySetting){const key=el.dataset.lobbySetting,value=key==='capacity'?Number(el.dataset.value):key==='random'?el.dataset.value==='true':el.dataset.value;await api('lobby-settings',{[key]:value});}}catch(error){toast(error.message);}});
document.addEventListener('change',async e=>{if(e.target.id!=='lobby-hard')return;try{await api('lobby-settings',{hard:Number(e.target.value)});}catch(error){toast(error.message);}});
document.addEventListener('submit',async e=>{if(e.target.id!=='lobby-chat-form')return;e.preventDefault();const input=document.querySelector('#lobby-chat-input'),text=input.value.trim();if(!text)return;try{await api('lobby-chat',{text});input.value='';}catch(error){toast(error.message);}});

function shop(){content.classList.remove('manual-page');document.body.classList.add('shop-mode');content.innerHTML=`<section class="shop-screen"><div class="shop-banner"><span>THE GUARDIAN'S COLLECTION</span><h1>수호자의 취향을 담다</h1><p>당신만의 모습으로 전장을 준비하세요.</p></div><div class="shop-layout"><section class="shop-catalog"><div class="shop-toolbar"><div class="shop-tabs" role="tablist" aria-label="상품 분류">${['전체','캐릭터 외형','프로필','꾸미기'].map((name,i)=>'<button role="tab" aria-selected="'+(i===0)+'" data-shop-category="'+name+'" class="'+(i===0?'selected':'')+'">'+name+'</button>').join('')}</div><input id="shop-search" aria-label="상품 검색" placeholder="상품 이름으로 검색하기…"></div><div class="shop-empty"><div class="shop-empty-symbol">✧</div><h2>새로운 컬렉션을 준비하고 있습니다</h2><p id="shop-empty-message">등록된 상품이 없습니다.</p><div class="shop-empty-line"></div><small>수호자의 새로운 모습이 이곳에 찾아옵니다.</small></div></section><aside class="shop-detail"><div class="shop-detail-heading"><span>COLLECTION PREVIEW</span><h2>상품 미리보기</h2><p>상품이 등록되면 상세 정보를 확인할 수 있습니다.</p></div><div class="shop-preview-empty"><div>✥</div><span>YOUR NEXT LOOK</span></div><div class="shop-detail-note">ⓘ 외형 전용 · 전투 능력치에 영향 없음</div><div class="shop-purchase-empty"><span>상품 등록 준비 중</span><button disabled>구매하기</button></div><button class="shop-preview-button" disabled>◎ 미리보기</button></aside></div></section>`;}
document.addEventListener('click',e=>{const b=e.target.closest('[data-shop-category]');if(!b)return;document.querySelectorAll('[data-shop-category]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-selected',String(x===b));});document.querySelector('#shop-empty-message').textContent=b.dataset.shopCategory==='전체'?'등록된 상품이 없습니다.':b.dataset.shopCategory+' 상품이 아직 등록되지 않았습니다.';});
document.addEventListener('input',e=>{if(e.target.id==='shop-search')document.querySelector('#shop-empty-message').textContent=e.target.value.trim()?'검색 결과가 없습니다.':'등록된 상품이 없습니다.';});

document.addEventListener('change',e=>{if(e.target.id==='boss-sound')globalThis.loopBossMuted=!e.target.checked;});

function requestChampionSale(ids){
 if(document.querySelector('#champion-sale-dialog')||!connected)return;
 const owner=me()?.id,gameId=game,chosen=[...new Set(ids)].filter(id=>me()?.champions.some(c=>c.id===id));if(!chosen.length)return;
 const dialog=document.createElement('dialog');dialog.id='champion-sale-dialog';dialog.innerHTML='<h3>판매하시겠습니까?</h3><p>선택한 챔피언 '+chosen.length+'명 · 총 '+chosen.length*15+'골드<br>장착 장비는 가방으로 반환됩니다.</p><div><button data-sale-yes>YES · 판매</button><button data-sale-no autofocus>NO · 취소</button></div>';document.body.append(dialog);
 dialog.addEventListener('close',()=>dialog.remove());dialog.querySelector('[data-sale-no]').onclick=()=>dialog.close();
 dialog.querySelector('[data-sale-yes]').onclick=async()=>{dialog.querySelectorAll('button').forEach(b=>b.disabled=true);try{if(game!==gameId&&(!$('#arena')||me()?.id!==owner))return;for(const id of chosen){if(!$('#arena')||me()?.id!==owner||!connected)break;if(!me().champions.some(c=>c.id===id))continue;if(!await act({type:'sell',id}))break;}}finally{dialog.close();}};
 dialog.showModal();
}

$('#auth-login-close').onclick=()=>$('#login').close();
$('#nickname-close').onclick=()=>$('#nickname-dialog').close();
$('#new-nickname').oninput=()=>{$('#nickname-status').textContent='';};
$('#nickname-check').onclick=async()=>{const name=$('#new-nickname').value;try{const r=await api('nickname-check',{name});if($('#new-nickname').value!==name)return;$('#nickname-status').textContent=r.available?'✓ 사용 가능한 닉네임입니다.':'이미 사용 중인 닉네임입니다.';$('#nickname-status').style.color=r.available?'#b8e684':'#ff9b98';}catch(e){$('#nickname-status').textContent=e.message;}};
$('#nickname-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const r=await api('nickname',{name:$('#new-nickname').value});setUser(r.user);$('#nickname-dialog').close();home();}catch(err){$('#nickname-status').textContent=err.message;}finally{button.disabled=false;}};
