import test from 'node:test';import assert from 'node:assert/strict';
import {createGame,action,tick,stats,position,championBoard,autoDispatchChampions} from './engine.js';
import {bossBoardIndex} from './encounters.js';
const hero=(id,base=2)=>({id,base,tier:0,x:180,y:145,equipment:{},cd:0});
function setup(mode='single',count=1){return createGame(Array.from({length:count},(_,i)=>({id:String(i)})),{mode});}
function spawn(g){g.status='playing';g.round=4;g.boards.forEach(b=>b.round=4);tick(g,.01);}
test('preselected heroes dispatch on boss appearance in all modes within their own boss range',()=>{for(const mode of ['single','versus','coop']){const g=setup(mode,mode==='single'?1:2);for(const [i,p] of g.players.entries()){p.champions=[hero(100+i),hero(200+i,0)];action(g,p.id,{type:'autoBoss',id:100+i,enabled:true});}spawn(g);for(const [i,p]of g.players.entries()){const c=p.champions[0],bi=bossBoardIndex(g,i),point=position(0,g.boards[bi].monsters[0]);assert.equal(c.world,true);assert.equal(championBoard(g,c),bi);assert.ok(Math.hypot(c.x-point.x,c.y-point.y)<stats(c).range/g.mapScale);assert.ok(!p.champions[1].world);assert.equal(c.destination,undefined);}}});
test('toggle while boss is alive dispatches immediately, rejects other players, and disabling does not teleport',()=>{const g=setup('versus',2),c=hero(100);g.players[0].champions=[c];spawn(g);assert.ok(action(g,'1',{type:'autoBoss',id:100,enabled:true}));assert.ok(action(g,'0',{type:'autoBoss',id:100,enabled:'yes'}));action(g,'0',{type:'autoBoss',id:100,enabled:true});assert.equal(c.world,true);const old={x:c.x,y:c.y};action(g,'0',{type:'autoBoss',id:100,enabled:false});assert.equal(c.world,true);assert.deepEqual({x:c.x,y:c.y},old);});
test('manual dispatch also places ranged and melee heroes inside range without overlap',()=>{const g=setup(),p=g.players[0];p.champions=Array.from({length:5},(_,i)=>hero(100+i,i%2?11:0));spawn(g);for(const c of p.champions)assert.equal(action(g,'0',{type:'dispatch',id:c.id}),undefined);for(const c of p.champions){assert.ok(Math.hypot(c.x-400,c.y-360)<=stats(c).range);for(const other of p.champions)if(c!==other)assert.ok(Math.hypot(c.x-other.x,c.y-other.y)>=44-.001);}});
test('manual return skips this boss; a later boss triggers again; death restores original placement',()=>{const g=setup(),p=g.players[0],c=hero(100);p.champions=[c];action(g,'0',{type:'autoBoss',id:100,enabled:true});spawn(g);action(g,'0',{type:'dispatch',id:100});assert.equal(c.world,false);assert.deepEqual({x:c.x,y:c.y},{x:180,y:145});autoDispatchChampions(g,true);assert.equal(c.world,false);g.boards[1].monsters=[];g.round=9;g.boards[0].round=9;g.boards[0].spawn=[];g.boards[0].monsters=[];tick(g,.01);assert.equal(c.world,true);g.boards[1].monsters[0].hp=0;tick(g,.01);assert.equal(c.world,false);assert.equal(c.autoBoss,true);assert.deepEqual({x:c.x,y:c.y},{x:180,y:145});});
test('crowded cooperative arena queues overflow rather than stacking champions',()=>{const g=setup('coop',4);g.players.forEach((p,i)=>p.champions=Array.from({length:30},(_,j)=>({...hero(100+i*30+j,11),autoBoss:true})));spawn(g);const sent=g.players.flatMap(p=>p.champions).filter(c=>c.world);assert.equal(sent.length,20);for(const p of g.players)assert.equal(p.champions.filter(c=>c.world).length,5);for(const c of sent){assert.ok(Math.hypot(c.x-400,c.y-360)<=stats(c).range);for(const other of sent)if(c!==other)assert.ok(Math.hypot(c.x-other.x,c.y-other.y)>=44-.001);}const waiting=g.players.flatMap(p=>p.champions).filter(c=>!c.world);assert.ok(waiting.every(c=>c.autoBoss));});
