import {encounterScope,mirrorBossEvents} from './encounters.js';
// Shared display metadata; warning time follows simulation time, including pause/speed.
export const BOSS_SKILL_ART='/assets/boss-skills-v1.png';
export const BOSS_SKILL_INFO=[
 {name:'공포의 포효',color:'#ce8aff',description:'아군 전체 · 5초 동안 공격 불가'},
 {name:'쇠약의 저주',color:'#78cfff',description:'아군 전체 · 10초 동안 공격속도 50% 감소'},
 {name:'재생의 파동',color:'#83f39c',description:'생존 몬스터 전체 · 최대 체력의 20% 회복'},
 {name:'광폭 행진',color:'#ff916d',description:'몬스터 전체 · 10초 동안 이동속도 50% 증가'},
 {name:'철벽 보호막',color:'#ffe190',description:'몬스터 전체 · 10초 동안 받는 피해 50% 감소'},
 {name:'서리 폭풍',color:'#9de9ff',description:'서리바람 · 6초 동안 공격속도 50% 감소'},
 {name:'암흑 장막',color:'#a991ee',description:'어둠 · 8초 동안 사거리 40% 감소'},
 {name:'마력 봉인',color:'#ed99e7',description:'8초 동안 챔피언 고유 스킬 사용 불가'},
];
export function bossWarnings(board,time){return [...(board?.monsters||[]),...(board?.remoteBosses||[])].filter(m=>m.boss&&m.hp>0&&Number.isFinite(m.nextSkillAt)&&m.nextSkillAt-time>0&&m.nextSkillAt-time<=3+1e-8).map(m=>({bossId:m.id,skill:(m.skillIndex||0)%BOSS_SKILL_INFO.length,remaining:m.nextSkillAt-time,p:m.p,worldBoss:m.worldBoss})).sort((a,b)=>a.remaining-b.remaining||a.bossId-b.bossId);}
export function activeBossCasts(board,time){return (board?.bossCasts||(board?.bossCast?[board.bossCast]:[])).filter(c=>c.until>time);}
export function bossIconMarkup(skill){return `<span class="boss-skill-icon" aria-hidden="true" style="background-position:${(skill%5)*25}% 0%"></span>`;}
export function bossNoticeMarkup(board,time){const warnings=bossWarnings(board,time),casts=activeBossCasts(board,time);return [...warnings.map(w=>({...w,warning:true})),...casts].map(v=>{const info=BOSS_SKILL_INFO[v.skill];return `<div class="boss-skill-card ${v.warning?'is-warning':'is-cast'}" style="--skill-color:${info.color}">${bossIconMarkup(v.skill)}<div><strong>${v.warning?'발동 예고':'스킬 발동'} · ${info.name}</strong><small>${info.description}</small>${v.warning?`<progress max="3" value="${Math.max(0,v.remaining)}" aria-label="발동까지 남은 시간"></progress>`:''}</div><b>${v.warning?Math.ceil(v.remaining)+'초':'발동'}</b></div>`;}).join('');}

export class BossSkillVisuals{
 constructor(){this.arrivalFrames=['/assets/boss-arrival-a.png','/assets/boss-arrival-b.png'].map(src=>{const image=new Image();image.src=src;return image;});this.frames=new Image();this.frames.src='/assets/boss-spell-frames-v2.png';this.image=new Image();this.image.src=BOSS_SKILL_ART;this.heard=new Set();}
 sprite(ctx,skill,row,x,y,size,alpha=1){if(!this.image.complete||!this.image.naturalWidth)return;const w=this.image.naturalWidth/5,h=this.image.naturalHeight/2;ctx.save();ctx.globalAlpha=alpha;ctx.globalCompositeOperation='screen';ctx.drawImage(this.image,(skill%5)*w,row*h,w,h,x-size/2,y-size/2,size,size);ctx.restore();}
 frame(ctx,skill,age,x,y,size,alpha=1){const image=this.frames;if(!image?.complete||!image.naturalWidth){this.sprite(ctx,skill,1,x,y,size,alpha);return;}const w=image.naturalWidth/4,h=image.naturalHeight/8,phase=(age*6)%6,index=[0,1,2,3,2,1][Math.floor(phase)];ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(image,index*w,skill*h,w,h,x-size/2,y-size/2,size,size);ctx.restore();}
 sounds(game,board){for(const cast of activeBossCasts(board,game.time)){const key=cast.bossId+':'+cast.born;if(this.heard.has(key))continue;this.heard.add(key);if(game.time-cast.born<.7)playBossSound(cast.skill);if(this.heard.size>100)this.heard.delete(this.heard.values().next().value);}}
 draw(ctx,game,board,owners,positions,verticalScale,position){
  ctx.save();const density=ctx.getTransform().a;ctx.setTransform(density,0,0,density,0,0);ctx.textAlign='center';
  const time=game.time,warnings=bossWarnings(board,time),casts=activeBossCasts(board,time);
  for(const cast of board.arrivalCasts||[]){if(cast.until<=time)continue;const age=time-cast.born,image=this.arrivalFrames[Math.floor(cast.id/7)],frame=Math.min(3,Math.floor(age/3*4)),info=BOSS_ARRIVALS[cast.id],h=800*verticalScale;ctx.save();ctx.fillStyle='#05091955';ctx.fillRect(0,0,800,h);if(image.complete&&image.naturalWidth){const w=image.naturalWidth/4,sh=image.naturalHeight/7;ctx.globalAlpha=Math.min(1,(3-age)*2);ctx.drawImage(image,frame*w,(cast.id%7)*sh,w,sh,200,h/2-110,400,220);}ctx.globalAlpha=1;ctx.fillStyle='#070d18e8';ctx.fillRect(150,16,500,55);ctx.fillStyle='#ffce89';ctx.font='bold 17px sans-serif';ctx.fillText('등장 스킬 · '+info.name,400,38);ctx.fillStyle='#e2eafa';ctx.font='12px sans-serif';ctx.fillText(info.description,400,58);ctx.restore();}

  for(const cast of casts){const age=time-cast.born,remaining=cast.until-time,fade=Math.min(1,age*3,remaining*2);if(fade<=0)continue;const key=cast.bossId+':'+cast.born;if(!this.heard.has(key)){this.heard.add(key);if(age<.7)playBossSound(cast.skill);if(this.heard.size>100)this.heard.delete(this.heard.values().next().value);}const h=800*verticalScale,info=BOSS_SKILL_INFO[cast.skill];ctx.save();ctx.globalAlpha=fade;if([0,6,7].includes(cast.skill)){ctx.fillStyle=cast.skill===6?'#09031cab':'#160a284d';ctx.fillRect(0,0,800,h);}if([1,5].includes(cast.skill)){ctx.fillStyle='#84dfff18';ctx.fillRect(0,0,800,h);ctx.strokeStyle='#c1efff99';ctx.lineWidth=2;for(let i=0;i<65;i++){const x=(i*113+time*155)%930-65,y=(i*67+time*24)%h;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-32,y+10);ctx.stroke();}}else{ctx.strokeStyle=info.color+'77';ctx.lineWidth=2;for(let i=0;i<4;i++){const radius=((age*90+i*85)%400)+20;ctx.beginPath();ctx.ellipse(400,h/2,radius,radius*verticalScale,0,0,Math.PI*2);ctx.stroke();}}this.frame(ctx,cast.skill,age,400,h/2,Math.min(380,h*.7),fade*.65);ctx.fillStyle='#030916c9';ctx.fillRect(245,15,310,44);ctx.fillStyle=info.color;ctx.font='bold 18px sans-serif';ctx.fillText(info.name+' · '+Math.ceil(remaining)+'초',400,43);ctx.restore();}
  for(const warning of warnings){const raw=positions.get(warning.bossId)||position(warning.p,warning),x=raw.x,y=raw.y*verticalScale,info=BOSS_SKILL_INFO[warning.skill];this.sprite(ctx,warning.skill,1,x,y,82+Math.sin(time*8)*5,.5);this.sprite(ctx,warning.skill,0,x,y-44,38);ctx.fillStyle='#070b16e8';ctx.fillRect(x-25,y-77,50,20);ctx.fillStyle=info.color;ctx.font='bold 13px sans-serif';ctx.fillText(Math.ceil(warning.remaining)+'초',x,y-62);}
  for(const cast of casts){const age=Math.max(0,time-(cast.born??cast.until-4));if(age>1.6)continue;const alpha=Math.max(0,1-age/1.6);const targets=[0,1,5,6,7].includes(cast.skill)?owners.flatMap(p=>p.champions).filter(c=>!!c.world===!!board.world):board.monsters;for(const target of targets){const point=positions.get(target.id)||(target.p===undefined?target:position(target.p,target));this.frame(ctx,cast.skill,age,point.x,point.y*verticalScale,68+age*25,alpha*.85);}}
  for(const c of owners.flatMap(p=>p.champions)){const point=positions.get(c.id)||c;let offset=0;for(const [skill,until]of [[0,c.fearUntil],[1,c.slowAttackUntil]]){if(!(until>time))continue;const x=point.x+offset,y=point.y*verticalScale-39;this.sprite(ctx,skill,0,x,y,26);ctx.font='bold 10px sans-serif';ctx.fillStyle=BOSS_SKILL_INFO[skill].color;ctx.fillText(Math.ceil(until-time)+'s',x,y-16);offset+=29;}}
  ctx.restore();
 }
}

let bossAudio;export function unlockBossAudio(){try{const Audio=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Audio)return;bossAudio??=new Audio();bossAudio.resume().catch(()=>{});}catch{}}
if(typeof document!=='undefined'){document.addEventListener('pointerdown',unlockBossAudio,{once:true});document.addEventListener('keydown',unlockBossAudio,{once:true});}
function playBossSound(skill){if(!bossAudio||bossAudio.state!=='running'||globalThis.loopBossMuted)return;const now=bossAudio.currentTime;for(let i=0;i<3;i++){const o=bossAudio.createOscillator(),gain=bossAudio.createGain();o.type=[0,6].includes(skill)?'sawtooth':'sine';const f=[90,330,520,180,240,640,65,410][skill];o.frequency.setValueAtTime(f*(1+i*.25),now);o.frequency.exponentialRampToValueAtTime(Math.max(30,f*.45),now+1.2);gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.025,now+.08);gain.gain.exponentialRampToValueAtTime(.001,now+1.3);o.connect(gain);gain.connect(bossAudio.destination);o.start(now);o.stop(now+1.4);o.onended=()=>{o.disconnect();gain.disconnect();};}if(skill===5||skill===1){const buffer=bossAudio.createBuffer(1,bossAudio.sampleRate*1.5,bossAudio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.15;const source=bossAudio.createBufferSource(),gain=bossAudio.createGain(),filter=bossAudio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=1200;source.buffer=buffer;gain.gain.setValueAtTime(.25,now);gain.gain.exponentialRampToValueAtTime(.001,now+1.5);source.connect(filter);filter.connect(gain);gain.connect(bossAudio.destination);source.start();}}

export const BOSS_ARRIVALS=[
 ['비취의 결계','보스 8초 보호막 · 피해 50% 감소'],['홍염 진군','몬스터 전체 6초 가속'],['영구동토','아군 전체 5초 공속 50% 감소'],['심연의 시선','아군 전체 6초 사거리 40% 감소'],['왕의 포효','아군 전체 2초 공포 · 보스 4초 보호막'],['망자의 숨결','아군 전체 5초 스킬 봉인'],['파쇄의 함성','가장 가까운 아군 3명 3초 공포'],['천뢰 강림','가장 가까운 아군 4명 4초 공속 감소 · 몬스터 3초 가속'],['맹독 거미줄','아군 전체 3초 공속 감소 · 스킬 봉인'],['사막의 장막','아군 전체 4초 사거리 감소 · 보스 5초 보호막'],['천상의 성벽','몬스터 전체 5초 보호막'],['삼중 악몽','가장 가까운 아군 3명 2초 공포 · 5초 사거리 감소'],['불사의 불꽃','생존 몬스터 15% 회복 · 보스 3초 보호막'],['해일의 축복','생존 몬스터 10% 회복 · 전체 4초 가속']
].map(([name,description],id)=>({id,name,description}));
export function castBossArrival(g,b,owners,boss){if(!boss.boss||boss.hp<=0||boss.arrivalUsed)return false;boss.arrivalUsed=true;const scope=encounterScope(g,b);if(b.world)owners=scope.players;const id=boss.bossVariant??Math.max(0,Math.floor(boss.round/5)-1)%14;const t=((boss.p||0)%1)*4,point=boss.worldBoss?{x:400,y:360}:t<1?{x:80+t*640,y:80}:t<2?{x:720,y:80+(t-1)*640}:t<3?{x:720-(t-2)*640,y:720}:{x:80,y:720-(t-3)*640};const all=owners.flatMap(p=>p.champions),near=[...all].sort((a,z)=>Math.hypot(a.x-point.x,a.y-point.y)-Math.hypot(z.x-point.x,z.y-point.y));const debuff=(list,key,d)=>list.forEach(c=>c[key]=Math.max(c[key]||0,g.time+d));const monsters=scope.boards.flatMap(board=>board.monsters).filter(m=>m.hp>0);const shield=(list,d)=>list.forEach(m=>m.shield=Math.max(m.shield||0,d));const haste=d=>monsters.forEach(m=>m.haste=Math.max(m.haste||0,d));const heal=p=>monsters.forEach(m=>m.hp=Math.min(m.maxHp,m.hp+m.maxHp*p));switch(id){case 0:shield([boss],8);break;case 1:haste(6);break;case 2:debuff(all,'slowAttackUntil',5);break;case 3:debuff(all,'blindUntil',6);break;case 4:debuff(all,'fearUntil',2);shield([boss],4);break;case 5:debuff(all,'silenceUntil',5);break;case 6:debuff(near.slice(0,3),'fearUntil',3);break;case 7:debuff(near.slice(0,4),'slowAttackUntil',4);haste(3);break;case 8:debuff(all,'slowAttackUntil',3);debuff(all,'silenceUntil',3);break;case 9:debuff(all,'blindUntil',4);shield([boss],5);break;case 10:shield(monsters,5);break;case 11:debuff(near.slice(0,3),'fearUntil',2);debuff(near.slice(0,3),'blindUntil',5);break;case 12:heal(.15);shield([boss],3);break;case 13:heal(.1);haste(4);break;}mirrorBossEvents(g,b,'arrivalCasts',{bossId:boss.id,id,born:g.time,until:g.time+3});return true;}
