import test from 'node:test';import assert from 'node:assert/strict';
import {createGame,tick,stats,damage,recordDamage,position,ELEMENTS,action} from './engine.js';
import {CHAMPION_SKILLS,tryChampionSkill,updateChampionSkills,skillMarkup} from './champion-skills.js';
const api={stats,damage,recordDamage,position,elements:ELEMENTS};
function scene(type,tier=4){const g=createGame([{id:'a'},{id:'b'}],{mode:'coop'});g.status='playing';g.round=1;g.mapScale=1;const b=g.boards[0];b.round=1;const p=g.players[0],c={id:10,base:type,tier,x:400,y:140,cd:100,equipment:{},skillReadyAt:0,combatState:'attacking'};p.champions=[c];g.players[1].champions=[{id:11,base:0,tier:4,x:450,y:140,cd:100,equipment:{}}];b.monsters=Array.from({length:5},(_,i)=>({id:100+i,family:0,p:.12+i*.008,hp:1e6,maxHp:1e6,speed:0,defenses:[],slow:0,stun:0,shred:0,poison:0,boss:false}));return {g,b,p,c};}
const cast=({g,b,p,c})=>tryChampionSkill(g,b,g.players,p,c,b.monsters,api);
test('all twenty skills cast with cooldown, art event and real damage or buffs',()=>{for(let type=0;type<20;type++){const sceneData=scene(type),{g,b,c}=sceneData;assert.equal(cast(sceneData),true,CHAMPION_SKILLS[type].name);assert.ok(c.skillReadyAt>0);assert.ok(g.skillEffects.some(e=>e.type===type));g.time=4;updateChampionSkills(g,b,g.players,api);if([6,9].includes(type))assert.ok(g.players.flatMap(p=>p.champions).some(c=>Object.keys(c.supportBuffs||{}).length));else{assert.ok(b.monsters.some(m=>m.hp<1e6),`damage ${type}`);assert.ok(c.damageLog?.length,`DPS ${type}`);}assert.ok(!skillMarkup(c,4).includes('undefined'));}});
test('locked tiers, movement, fear, absent targets and cooldown do not spend skill',()=>{for(const condition of ['tier','moving','fear','targets','cooldown']){const x=scene(4);if(condition==='tier')x.c.tier=2;if(condition==='moving')x.c.destination={x:500,y:300};if(condition==='fear')x.c.fearUntil=10;if(condition==='targets')x.b.monsters=[];if(condition==='cooldown')x.c.skillReadyAt=10;const old=x.c.skillReadyAt;assert.equal(cast(x),false);assert.equal(x.c.skillReadyAt,old);assert.equal(x.g.skillEffects,undefined);}});
test('meteor delayed damage and bomb following preserve location, DPS and kill credit',()=>{for(const type of [4,8]){const x=scene(type),{g,b,c}=x;cast(x);assert.ok(b.monsters.every(m=>m.hp===1e6));const first=g.skillPending[0];if(type===8){b.monsters[0].p=.3;g.time=1;updateChampionSkills(g,b,g.players,api);assert.deepEqual(first.center,position(.3));}g.time=first.at;updateChampionSkills(g,b,g.players,api);assert.ok(b.monsters.some(m=>m.hp<1e6));assert.ok(c.damageLog.length);assert.ok(b.monsters.some(m=>m.lastHit==='a'));}});
test('legendary blessing skips already buffed allies and cleanses eligible targets',()=>{const x=scene(9,6);x.p.champions.push({id:12,base:2,tier:4,x:350,y:140,cd:100,equipment:{},fearUntil:10,supportBuffs:{damage:{amount:2,until:100},speed:{amount:2,until:100}}});x.g.players[1].champions[0].fearUntil=10;cast(x);assert.equal(x.p.champions[1].fearUntil,10);assert.equal(x.g.players[1].champions[0].fearUntil,0);assert.equal(x.p.champions[1].supportBuffs.damage.amount,2);assert.equal(x.p.champions[1].supportBuffs.speed.amount,2);});
test('ice skill slows boss instead of full freeze; assassin refunds on kill',()=>{let x=scene(3);x.b.monsters[0].boss=true;cast(x);assert.equal(x.b.monsters[0].stun,0);assert.equal(x.b.monsters[0].slowAmount,.6);assert.equal(x.b.monsters[1].stun,2);x=scene(11);x.b.monsters[0].hp=1;cast(x);assert.equal(x.c.skillReadyAt,6);});
test('engine auto casts after cooldown, pause freezes timers, skill kills reward the killer and count once',()=>{const x=scene(14),{g,b,c,p}=x;b.monsters=b.monsters.slice(0,1);b.monsters[0].hp=1;g.status='paused';tick(g,1);assert.equal(g.time,0);g.status='playing';tick(g,.05);assert.equal(p.kills,1);assert.equal(p.gold,61);assert.equal(g.players[1].gold,60);assert.ok(c.lastSkill);tick(g,.05);assert.equal(p.kills,1);});
test('delayed skills on one versus board cannot damage other board',()=>{const x=scene(4);x.g.mode='versus';x.g.boards[1]=({monsters:[{...x.b.monsters[0]}],spawn:[],round:1});cast(x);x.g.time=5;updateChampionSkills(x.g,x.g.boards[1],[x.g.players[1]],api);assert.equal(x.g.boards[1].monsters[0].hp,1e6);assert.ok(x.g.skillPending.length);});

test('rare champions unlock every active skill and normal remains locked',()=>{for(let type=0;type<20;type++){const x=scene(type,3);assert.equal(cast(x),true,'rare skill '+type);assert.ok(!skillMarkup(x.c,0).includes('등급부터 해금'));}const x=scene(0,2);assert.equal(cast(x),false);assert.ok(skillMarkup(x.c,0).includes('레어 등급부터 해금'));});
