import test from 'node:test';import assert from 'node:assert/strict';
import {createGame,action,tick,monster,monsterCount,chainStats,chainTargets,stats,castBossSkill} from './engine.js';
import {tryChampionSkill} from './champion-skills.js';
const users=[{id:'a'},{id:'b'}];
test('silence prevents champion skill casting before touching its targets or cooldown',()=>{const c={silenceUntil:30,skillReadyAt:1};assert.equal(tryChampionSkill({time:20},{},[],{},c,[],{}),false);assert.equal(c.skillReadyAt,1);});
test('legendary chain deals real damage to three extra enemies with one attack',()=>{const g=createGame([{id:'a'}]);g.status='playing';g.round=1;g.boards[0].round=1;const c={id:900,base:0,tier:0,x:400,y:145,cd:0,equipment:{0:{base:7,tier:6}}};g.players[0].champions=[c];g.boards[0].monsters=Array.from({length:4},(_,i)=>({...monster(g,{round:1,boss:false}),p:.1+i*.02,hp:10000,maxHp:10000,speed:0}));tick(g,.01);assert.equal(g.effects.filter(e=>e.chain).length,3);assert.ok(g.boards[0].monsters.every(m=>m.hp<10000));assert.equal(g.players[0].champions[0].damageLog.length,1);});
test('split equipment chances cap at 100%, epic and legendary never stack',()=>{
 for(const [tier,chance,count] of [[0,.2,1],[1,.3,1],[2,.5,1],[3,.8,1],[4,1,1],[5,1,2],[6,1,3]]){assert.deepEqual(chainStats({equipment:{0:{base:7,tier}}}),{chainChance:chance,chainCount:count});}
 assert.deepEqual(chainStats({equipment:{0:{base:7,tier:3},1:{base:17,tier:3}}}),{chainChance:1,chainCount:1});
 assert.deepEqual(chainStats({equipment:{0:{base:7,tier:6},1:{base:17,tier:6},2:{base:27,tier:5}}}),{chainChance:1,chainCount:3});
 assert.equal(stats({base:0,tier:0,equipment:{0:{base:7,tier:6}}}).targets,1);
});
test('chain follows distinct adjacent enemies, respects probability and range',()=>{const mobs=Array.from({length:5},(_,i)=>({id:i,p:i*.02,hp:100}));assert.equal(chainTargets([mobs[0]],mobs,{chainChance:.2,chainCount:1},()=>.3).length,0);const links=chainTargets([mobs[0]],mobs,{chainChance:1,chainCount:3},()=>0);assert.deepEqual(links.map(l=>l.to.id),[1,2,3]);assert.equal(chainTargets([mobs[0]],[mobs[0],{id:9,p:.5,hp:100}],{chainChance:1,chainCount:3},()=>0).length,0);});
test('single and versus boss counts as ten, co-op retains one',()=>{for(const mode of ['single','versus','coop']){const g=createGame(users,{mode}),b=g.boards[0];b.monsters=[monster(g,{round:5,boss:true})];assert.equal(monsterCount(g,b),mode==='coop'?1:10);if(mode!=='coop'){b.monsters.push(...Array.from({length:90},()=>monster(g,{round:1,boss:false})));g.status='playing';tick(g,.01);assert.equal(mode==='single'?g.status:g.players[0].alive,mode==='single'?'ended':false);}}});
test('versus first clear grants five gold once and does not pay opponent',()=>{const g=createGame(users,{mode:'versus'});action(g,'a',{type:'start'});g.boards[0].spawn=[];tick(g,.01);assert.equal(g.round,2);assert.equal(g.players[0].gold,65);assert.equal(g.players[1].gold,60);tick(g,.01);assert.equal(g.players[0].gold,65);});
test('boss fear lasts five seconds and new spells apply timed debuffs',()=>{const g=createGame(users),c={id:1,base:0,tier:0,x:400,y:400,equipment:{}};g.players[0].champions=[c];g.time=20;for(const [skill,key,duration] of [[0,'fearUntil',5],[5,'slowAttackUntil',6],[6,'blindUntil',8],[7,'silenceUntil',8]]){castBossSkill(g,g.boards[0],g.players,{id:2,skillIndex:skill});assert.equal(c[key],20+duration);assert.equal(g.boards[0].bossCast.until,20+duration);}});
test('world boss survives timed next wave and only expires at next boss round',()=>{const g=createGame(users,{mode:'coop'});g.round=4;g.status='playing';g.boards.forEach(b=>b.round=4);tick(g,.01);const world=g.boards[2],id=world.monsters[0].id;for(let round=5;round<10;round++){g.boards.slice(0,2).forEach(b=>{b.spawn=[];b.monsters=[monster(g,{round,boss:false})];});g.time=g.roundStartedAt+60;tick(g,.01);if(round<9){assert.equal(g.status,'playing');assert.equal(world.monsters[0].id,id);}else assert.equal(g.status,'ended');}});
