import {equippedProduct,themeFor} from './cosmetics.js';
import {CosmeticArt} from './cosmetic-art.js';
// All cosmetics are visual only; no changes to movement, targeting, or damage.
export class CosmeticEffects{
 constructor(){this.births=new Map();this.game=null;this.art=new CosmeticArt();this.victoryAt=null;}
 receive(game,clock){if(!this.game||game.time<this.game.time){this.births.clear();this.victoryAt=game.status==='ended'?clock:null;this.game=game;for(const p of game.players)for(const c of p.champions)this.births.set(c.id,-999);return;}const old=new Set(this.game.players.flatMap(p=>p.champions.map(c=>c.id)));for(const p of game.players)for(const c of p.champions)if(!old.has(c.id))this.births.set(c.id,clock);const current=new Set(game.players.flatMap(p=>p.champions.map(c=>c.id)));for(const id of this.births.keys())if(!current.has(id))this.births.delete(id);if(game.status==='ended'&&this.game.status!=='ended')this.victoryAt=clock;this.game=game;}
 summon(ctx,c,owner,clock){const p=equippedProduct(owner.cosmetics,'summon'),age=clock-(this.births.get(c.id)??-999);if(!p||age<0||age>=2.2)return;const t=age/2.2,alpha=Math.min(1,t*8,(1-t)*3);this.art.draw(ctx,p,c.x,c.y+8,125+25*t,92+15*t,alpha,0);this.sparks(ctx,c.x,c.y,themeFor(p),t,12);}
 sparks(ctx,x,y,theme,t,count){ctx.save();ctx.fillStyle=theme.color;ctx.shadowColor=theme.color;ctx.shadowBlur=5;ctx.globalAlpha=Math.sin(Math.PI*t)*.7;for(let i=0;i<count;i++){const a=i*2.399,r=12+35*t+(i%3)*5,px=x+Math.cos(a)*r,py=y+Math.sin(a)*r*.45-t*25;ctx.beginPath();ctx.arc(px,py,1+i%2,0,Math.PI*2);ctx.fill();}ctx.restore();}
 deaths(ctx,game,board,position){for(const d of (game.deaths||[]).filter(d=>d.board===board)){const owner=game.players.find(p=>p.id===d.owner),p=equippedProduct(owner?.cosmetics,'kill');if(!p)continue;const age=game.time-d.born;if(age<0||age>1.5)continue;const at=position(d.p,d),t=age/1.5,size=65+Math.sin(t*Math.PI/2)*85;this.art.draw(ctx,p,at.x,at.y-12,size,size,Math.min(1,t*10)*(1-t));this.sparks(ctx,at.x,at.y,themeFor(p),t,8);}}
 victory(ctx,game,owner,clock){if(game.status!=='ended'||!owner)return;const won=game.mode==='versus'?owner.alive&&game.players.filter(p=>p.alive).length===1:game.message?.includes('100 ROUND CLEAR');const p=equippedProduct(owner.cosmetics,'victory');if(!won||!p)return;const age=clock-(this.victoryAt??clock),theme=themeFor(p),intro=Math.min(1,age/1.2);ctx.save();const shade=ctx.createRadialGradient(400,365,50,400,365,340);shade.addColorStop(0,'#020916d9');shade.addColorStop(1,'#02091600');ctx.fillStyle=shade;ctx.fillRect(40,90,720,600);const size=370+(1-intro)*60;this.art.draw(ctx,p,400,335,size,size,Math.max(.1,intro));ctx.textAlign='center';ctx.fillStyle='#fff3d2';ctx.shadowColor=theme.color;ctx.shadowBlur=18;ctx.font='bold 30px Georgia';ctx.fillText('VICTORY',400,365);ctx.shadowBlur=0;ctx.font='bold 15px sans-serif';ctx.fillStyle=theme.color;ctx.fillText(p.name,400,405);this.sparks(ctx,400,425,theme,(clock%4)/4,20);ctx.restore();}
}
