import {COSMETIC_BOUNDS} from './cosmetic-bounds.js';
import {THEMES,themeFor} from './cosmetics.js';
export const COSMETIC_ATLASES={effects:{src:'/assets/cosmetic-effects-v4.png',cols:4,rows:6},ornaments:{src:'/assets/cosmetic-ornaments-v3.png',cols:3,rows:6},emotes:{src:'/assets/cosmetic-emotes-v3.png',cols:3,rows:2}};
export function cosmeticTile(p){const row=Math.max(0,THEMES.findIndex(t=>t.id===p?.theme));if(p?.slot==='emote')return {...COSMETIC_ATLASES.emotes,col:row%3,row:Math.floor(row/3)};const effect=['entry','summon','kill','victory'].indexOf(p?.slot);if(effect>=0)return {...COSMETIC_ATLASES.effects,col:effect,row};const ornament=['frame','nameplate','title'].indexOf(p?.slot);return ornament>=0?{...COSMETIC_ATLASES.ornaments,col:ornament,row}:null;}
export function cosmeticRect(tile){const meta=COSMETIC_BOUNDS[tile.src],b=meta.cells[tile.row*tile.cols+tile.col];return {x:b.x/meta.width,y:b.y/meta.height,w:b.w/meta.width,h:b.h/meta.height};}
export function cosmeticArtMarkup(p,className=''){const tile=cosmeticTile(p);if(!tile)return '';const meta=COSMETIC_BOUNDS[tile.src],b=meta.cells[tile.row*tile.cols+tile.col];return `<span aria-hidden="true" class="cos-art ${className}" style="--cos-color:${themeFor(p).color}"><svg viewBox="${b.x} ${b.y} ${b.w} ${b.h}" preserveAspectRatio="xMidYMid meet"><defs><clipPath id="cos-${p.slot}-${tile.col}-${tile.row}"><rect x="${b.x}" y="${b.y}" width="${b.w}" height="${b.h}"/></clipPath></defs><image clip-path="url(#cos-${p.slot}-${tile.col}-${tile.row})" href="${tile.src}" width="${meta.width}" height="${meta.height}"/></svg></span>`;}
export class CosmeticArt{
 constructor(){this.images=new Map();for(const atlas of Object.values(COSMETIC_ATLASES)){const image=new Image();image.src=atlas.src;this.images.set(atlas.src,image);}}
 draw(ctx,p,x,y,w,h,alpha=1,rotation=0){const tile=cosmeticTile(p),image=tile&&this.images.get(tile.src);if(!image?.complete||!image.naturalWidth)return false;const r=cosmeticRect(tile),sw=image.naturalWidth*r.w,sh=image.naturalHeight*r.h;const scale=Math.min(w/sw,h/sh);w=sw*scale;h=sh*scale;const transform=ctx.getTransform(),vertical=Math.abs(transform.d/transform.a)||1;ctx.save();ctx.translate(x,y);ctx.scale(1,1/vertical);ctx.rotate(rotation);ctx.globalAlpha=Math.max(0,Math.min(1,alpha));ctx.drawImage(image,r.x*image.naturalWidth,r.y*image.naturalHeight,sw,sh,-w/2,-h/2,w,h);ctx.restore();return true;}
}
