import { controlAction, formationPosition, sortTargets } from './gameplay.js';
export function monsterProfile(game, round, boss = false) {
  const party = game.mode === 'coop' ? 1 + game.players.length * 0.3 : 1;
  return { hp: (28 + round * 7) * 1.022 ** (round - 1) * (1 + game.hard * 0.5) * (boss ? 10 : 1) * party };
}
export const TIERS=['커먼','언커먼','노말','레어','유니크','에픽','레전더리'];
export const COLORS=['#98abb9','#74cfaa','#68bafa','#b39aff','#ffcc72','#ff87b8','#fff0a1'];
export const TYPES=['총기','활','검','얼음','화염','대지','바람','독','폭탄','성장'];
export const ELEMENTS=['물리원거리','물리원거리','물리근거리','수','화','지','풍','독','화','물리근거리'];
export const IMMUNITIES=['물리원거리','물리근거리','수','풍','지','화','물리면역','마법면역','슬로우면역','방깎면역'];
export const SLOTS=['무기','장갑','신발','목걸이'];
const names=['아르','루나','카이','세라','레온','니아','제드','에린','노아','벨'];
export const CHAMPIONS=['저격수','궁수','검사','서리술사','화염술사','대지술사','바람술사','연금술사','폭파병','수확자'].map((name,i)=>({id:i,name,type:i}));
const itemNames=['맹공','신속','매의 눈','정밀','격노','관통','비전','분열','빙하','파쇄'];
export const ITEMS=Array.from({length:40},(_,i)=>({id:i,name:`${itemNames[i%10]}의 ${SLOTS[Math.floor(i/10)]}`,slot:Math.floor(i/10),effect:i%10}));
export function chances(level){const base=[90,5.556,2.667,1.222,.4,.133,.022],top=[10,18,25,24,14,7,2];const result=base.map((n,i)=>+(n+(top[i]-n)*(level-1)/9).toFixed(3));result[0]+=100-result.reduce((a,b)=>a+b,0);return result;}
export function roll(level,rng=Math.random){let n=rng()*100;const index=chances(level).findIndex(p=>(n-=p)<0);return index<0?6:index;}
export function position(p){p=((p%1)+1)%1;let t=p*4;return t<1?{x:80+640*t,y:80}:t<2?{x:720,y:80+640*(t-1)}:t<3?{x:720-640*(t-2),y:720}:{x:80,y:720-640*(t-3)};}
export function createGame(users,options={}){const mode=['single','coop','versus'].includes(options.mode)?options.mode:'single';return {mode,mapScale:mode==='coop'?1.4:1,random:!!options.random,hard:Math.max(0,Math.min(5,Number(options.hard)||0)),round:0,time:0,roundStartedAt:0,waveInterval:60,speed:2,status:'ready',nextId:1,effects:[],players:users.map(u=>({id:u.id,name:u.name,gold:60,kills:0,champions:[],items:[],heroLevel:1,itemLevel:1,alive:true})),boards:Array.from({length:mode==='versus'?users.length:1},()=>({monsters:[],spawn:[],round:0,cleared:0})),message:'챔피언을 소환하고 전투를 시작하세요.'};}
export function stats(c){const def=CHAMPIONS[c.base],t=def.type,m=1.7**c.tier;let s={attack:([27,12,37,15,32,19,9,12,25,28][t]+Math.floor(c.base/10)*.7)*m+(c.growth||0),speed:[.65,1.65,.85,.95,.65,.75,2.1,1.1,.65,.9][t],range:[370,275,145,280,260,230,280,260,280,155][t],crit:.08,critMult:1.7,armorPen:0,magicPen:0,targets:1,slow:0,shred:0};for(const it of Object.values(c.equipment)){if(!it)continue;const p=1.6**it.tier;switch(ITEMS[it.base].effect){case 0:s.attack+=10*p;break;case 1:s.speed*=1+.12*p;break;case 2:s.range+=20*p;break;case 3:s.crit+=.06*p;break;case 4:s.critMult+=.2*p;break;case 5:s.armorPen+=.08*p;break;case 6:s.magicPen+=.08*p;break;case 7:s.targets+=Math.max(1,Math.floor(p/2));break;case 8:s.slow+=.12*p;break;case 9:s.shred+=.12*p;break;}}s.crit=Math.min(.85,s.crit);s.range=Math.min(550,s.range);return s;}
function spawnRound(g){g.round++;g.roundStartedAt=g.time;g.message=`ROUND ${g.round} · ${g.round%10===0?'보스 출현':'방어선을 지키세요'}`;for(const [bi,b]of g.boards.entries()){if(g.mode==='versus'&&!g.players[bi].alive)continue;b.round=g.round;for(let i=0;i<30;i++)b.spawn.push({at:g.time+i*.28,round:g.round,boss:i===29&&g.round%10===0});}}
export function action(g,pid,a){const p=g.players.find(p=>p.id===pid);if(!p||!p.alive||g.status==='ended')return '현재 행동할 수 없습니다.';const control=controlAction(g,p,a);if(control!==undefined)return control;if(a.type==='start'){if(g.status==='ready'){g.status='playing';spawnRound(g);}return;}
if(a.type==='draw'){if(p.gold<30)return '골드가 부족합니다.';const hero=a.kind==='hero';if((hero?p.champions:p.items).length>=80)return '보유 한도는 80개입니다.';p.gold-=30;let item={id:g.nextId++,base:Math.floor(Math.random()*(hero?CHAMPIONS.length:40)),tier:roll(hero?p.heroLevel:p.itemLevel)};if(hero)Object.assign(item,{...formationPosition((p.champions.length+(g.mode==='coop'?g.players.indexOf(p)*8:0))%80),target:'smart',cd:0,equipment:{},growth:0});(hero?p.champions:p.items).push(item);return;}
if(a.type==='upgrade'){let key=a.kind==='hero'?'heroLevel':'itemLevel',cost=p[key]*40;if(p[key]>=10)return '최고 레벨입니다.';if(p.gold<cost)return '골드가 부족합니다.';p.gold-=cost;p[key]++;return;}
const c=p.champions.find(c=>c.id===a.id);
if(a.type==='moveGroup'&&Array.isArray(a.ids)&&Number.isFinite(a.x)&&Number.isFinite(a.y)){const chosen=p.champions.filter(c=>a.ids.includes(c.id)).slice(0,80);if(!chosen.length)return;const cx=chosen.reduce((s,c)=>s+c.x,0)/chosen.length,cy=chosen.reduce((s,c)=>s+c.y,0)/chosen.length;for(const hero of chosen){const target={x:Math.min(660,Math.max(140,a.x+(hero.x-cx))),y:Math.min(660,Math.max(140,a.y+(hero.y-cy)))};if(g.status==='ready'){Object.assign(hero,target);delete hero.destination;}else hero.destination=target;}return;}
if(a.type==='move'&&c&&Number.isFinite(a.x)&&Number.isFinite(a.y)){const target={x:Math.min(660,Math.max(140,a.x)),y:Math.min(660,Math.max(140,a.y))};if(g.status==='ready'){Object.assign(c,target);delete c.destination;}else c.destination=target;return;}
if(a.type==='equip'&&c){const i=p.items.findIndex(i=>i.id===a.item);if(i<0)return;const item=p.items.splice(i,1)[0],slot=ITEMS[item.base].slot;if(c.equipment[slot])p.items.push(c.equipment[slot]);c.equipment[slot]=item;return;}
if(a.type==='unequip'&&c&&c.equipment[a.slot]){p.items.push(c.equipment[a.slot]);delete c.equipment[a.slot];return;}
if(a.type==='merge'){const list=a.kind==='hero'?p.champions:p.items,first=list.find(i=>i.id===a.id);if(!first||first.tier===6)return '합성할 수 없습니다.';const other=list.find(i=>i.id!==first.id&&i.base===first.base&&i.tier===first.tier);if(!other)return '동일 이름·등급 2개가 필요합니다.';if(other.equipment)p.items.push(...Object.values(other.equipment));list.splice(list.indexOf(other),1);first.tier++;return;}}
function monster(g,s){let family=g.random?Math.floor(Math.random()*10):(s.round-1)%10;let defenses=[IMMUNITIES[family]];for(let j=0;j<g.hard;j++){let d=IMMUNITIES[(family+j+1)%10];if((d==='물리면역'&&defenses.includes('마법면역'))||(d==='마법면역'&&defenses.includes('물리면역')))continue;defenses.push(d);}const {hp}=monsterProfile(g,s.round,s.boss);return {id:g.nextId++,p:0,hp,maxHp:hp,speed:(.023+family*.001)*(1+g.hard*.05),family,defenses,boss:s.boss,slow:0,stun:0,shred:0,poison:0,poisonOwner:null};}
export function damage(mon,amount,element,s){if((element.startsWith('물리')&&mon.defenses.includes('물리면역'))||(['수','화','지','풍'].includes(element)&&mon.defenses.includes('마법면역')))return 0;let resistance=mon.defenses.includes(element)?.65:0;const pen=element.startsWith('물리')?s.armorPen:s.magicPen;return amount*(1-Math.max(0,resistance-pen-mon.shred));}
export function tick(g,dt){if(g.status!=='playing')return;g.time+=dt;g.effects=g.effects.filter(e=>e.until>g.time);for(const [bi,b]of g.boards.entries()){if(g.mode==='versus'&&!g.players[bi].alive)continue;while(b.spawn.length&&b.spawn[0].at<=g.time)b.monsters.push(monster(g,b.spawn.shift()));if(b.monsters.length>=100){if(g.mode==='versus'){g.players[bi].alive=false;b.spawn=[];continue;}g.status='ended';g.message='방어선 붕괴 · 몬스터 100마리';return;}const owners=g.mode==='versus'?[g.players[bi]]:g.players;
for(const m of b.monsters){m.stun=Math.max(0,m.stun-dt);if(!m.stun)m.p=(m.p+m.speed*dt/g.mapScale*(m.slow>0?.55:1))%1;m.slow=Math.max(0,m.slow-dt);if(m.poison>0){m.hp-=m.poison*dt;m.lastHit=m.poisonOwner;}}
for(const p of owners)for(const c of p.champions){if(c.destination){let dx=c.destination.x-c.x,dy=c.destination.y-c.y,d=Math.hypot(dx,dy),step=150*dt/g.mapScale;if(d<=step){c.x=c.destination.x;c.y=c.destination.y;delete c.destination;}else{c.x+=dx/d*step;c.y+=dy/d*step;}}c.cd-=dt;if(c.cd>0)continue;const s=stats(c),t=CHAMPIONS[c.base].type,near=sortTargets(b.monsters.filter(m=>m.hp>0&&Math.hypot(position(m.p).x-c.x,position(m.p).y-c.y)<=s.range/g.mapScale),c.target||'smart',m=>damage(m,1,ELEMENTS[t],s));if(!near.length)continue;const buff=owners.some(o=>o.champions.some(v=>v.tier>=4&&CHAMPIONS[v.base].type===6&&Math.hypot(v.x-c.x,v.y-c.y)<220/g.mapScale));c.cd=1/(s.speed*(buff?1.25:1));let targets=near.slice(0,s.targets);if(c.tier>=4&&[4,5,8].includes(t)){const origin=position(near[0].p);targets=near.filter(m=>Math.hypot(position(m.p).x-origin.x,position(m.p).y-origin.y)<100/g.mapScale);}for(const m of targets){const hit=damage(m,s.attack*(Math.random()<s.crit?s.critMult:1),ELEMENTS[t],s);m.hp-=hit;m.lastHit=p.id;if(hit>0){if((t===3||s.slow)&&!m.defenses.includes('슬로우면역')){m.slow=2;if(t===3&&c.tier>=4)m.stun=.5;}if(t===5)m.stun=c.tier>=4?.5:.18;if(s.shred&&!m.defenses.includes('방깎면역'))m.shred=Math.min(.6,m.shred+s.shred);if(t===7){m.poison=Math.max(m.poison,hit*.25);m.poisonOwner=p.id;}if(t===8&&c.tier>=4)m.hp-=hit*.35;}if(m.hp<=0&&t===9)c.growth+=1+c.tier;g.effects.push({source:c.id,x:c.x,y:c.y,...{tx:position(m.p).x,ty:position(m.p).y},color:COLORS[c.tier],until:g.time+.3,born:g.time,amount:Math.round(hit),type:t,board:bi});}}
for(const m of b.monsters.filter(m=>m.hp<=0)){const p=g.players.find(p=>p.id===m.lastHit);if(p){p.kills++;if(g.mode==='coop')g.players.forEach(q=>q.gold+=m.boss?30:1);else p.gold+=m.boss?30:1;}}b.monsters=b.monsters.filter(m=>m.hp>0);if(!b.monsters.length&&!b.spawn.length)b.cleared=b.round;}
if(g.mode==='versus'&&g.players.filter(p=>p.alive).length<=1){g.status='ended';g.message=`${g.players.find(p=>p.alive)?.name||'모두'} · 생존 승리`;return;}const active=g.boards.filter((b,i)=>g.mode!=='versus'||g.players[i].alive);if(active.some(b=>b.cleared===g.round)||(g.mode!=='versus'&&g.round<100&&g.time-g.roundStartedAt>=g.waveInterval-1e-8)){if(g.round<100)spawnRound(g);else if(active.every(b=>!b.monsters.length&&!b.spawn.length)){g.status='ended';g.message='100 ROUND CLEAR · 방어 성공';}}}
