import test from 'node:test';
import assert from 'node:assert/strict';
import {CHAMPIONS,ELEMENTS,stats,createGame,action,tick,championDamageMultiplier} from './engine.js';
const hero=(base,tier=0)=>({id:1,base,tier,x:400,y:140,equipment:{},cd:0});
function encounter(base,tier=0){const g=createGame([{id:'a'}]);g.status='playing';g.round=1;g.boards[0].round=1;g.players[0].champions=[hero(base,tier)];g.boards[0].monsters=Array.from({length:6},(_,i)=>({id:100+i,family:0,p:.12+i*.003,hp:1e5,maxHp:1e5,speed:0,defenses:[],slow:0,stun:0,shred:0,poison:0}));return g;}
test('all five new champions have finite stats in seven tiers and valid damage elements',()=>{assert.equal(CHAMPIONS.length,20);for(let base=10;base<20;base++)for(let tier=0;tier<7;tier++){const s=stats(hero(base,tier));for(const value of Object.values(s))assert.ok(Number.isFinite(value));assert.ok(s.attack>0&&s.speed>0&&s.range>0);assert.ok(ELEMENTS[base]);}});
test('lightning gains five targets and stun; tide hits four and slows at unique tier',()=>{for(const [base,count] of [[10,5],[13,4]]){const g=encounter(base,4);tick(g,.05);const hit=g.boards[0].monsters.filter(m=>m.hp<m.maxHp);assert.equal(hit.length,count);assert.ok(hit.every(m=>base===10?m.stun>0:m.slow>0));}});
test('dragon knight pierces armor and shreds two targets; assassin and gunner have conditional bonuses',()=>{const g=encounter(12,4);tick(g,.05);assert.equal(g.boards[0].monsters.filter(m=>m.shred>0).length,2);assert.equal(stats(hero(12)).armorPen,.2);assert.equal(stats(hero(11)).crit,.3);assert.equal(championDamageMultiplier(hero(11,4),{hp:30,maxHp:100}),1.5);assert.equal(championDamageMultiplier(hero(11,3),{hp:30,maxHp:100}),1);assert.equal(championDamageMultiplier(hero(14,4),{boss:true}),1.75);assert.equal(championDamageMultiplier(hero(14,4),{boss:false}),1);});
test('new champions draw from the same shop and merge while preserving equipped items',t=>{for(let base=10;base<20;base++){const g=createGame([{id:'a'}]),p=g.players[0];t.mock.method(Math,'random',()=>base/CHAMPIONS.length+.0001);action(g,'a',{type:'draw',kind:'hero'});assert.equal(p.champions[0].base,base);t.mock.restoreAll();p.champions=[hero(base),{...hero(base),id:2,equipment:{0:{id:3,base:0,tier:0}}}];action(g,'a',{type:'merge',kind:'hero',id:1});assert.equal(p.champions.length,1);assert.equal(p.champions[0].tier,1);assert.equal(p.items[0].id,3);}});
test('new champions cannot attack while following movement orders',()=>{for(let base=10;base<20;base++){const g=encounter(base,4);g.players[0].champions[0].destination={x:500,y:400};tick(g,.05);assert.ok(g.boards[0].monsters.every(m=>m.hp===m.maxHp));}});
