import { stepGame } from './gameplay.js';
import http from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {randomBytes,createPublicKey,verify} from 'node:crypto';
import {createGame,action,tick} from './engine.js';
const port=Number(process.env.PORT)||3000,clientId=process.env.GOOGLE_CLIENT_ID||'';
const sessions=new Map(),rooms=new Map();let rankings=[];
try{rankings=JSON.parse(await readFile(new URL('./data/rankings.json',import.meta.url),'utf8'));}catch{}
const id=()=>randomBytes(16).toString('hex');
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
let keys=[],keyUntil=0;
async function verifyGoogle(token){const parts=String(token).split('.');if(parts.length!==3)throw Error('잘못된 로그인 응답');const header=JSON.parse(Buffer.from(parts[0],'base64url')),claims=JSON.parse(Buffer.from(parts[1],'base64url'));if(header.alg!=='RS256')throw Error('지원하지 않는 서명');if(Date.now()>keyUntil){const r=await fetch('https://www.googleapis.com/oauth2/v3/certs');if(!r.ok)throw Error('Google 인증 서버 오류');keys=(await r.json()).keys;keyUntil=Date.now()+3600000;}const key=keys.find(k=>k.kid===header.kid);if(!key||!verify('RSA-SHA256',Buffer.from(parts[0]+'.'+parts[1]),createPublicKey({key,format:'jwk'}),Buffer.from(parts[2],'base64url'))||claims.aud!==clientId||!['https://accounts.google.com','accounts.google.com'].includes(claims.iss)||!Number.isFinite(claims.exp)||claims.exp*1000<Date.now()||!claims.sub)throw Error('Google 인증 검증 실패');return claims;}
function summary(r){return {id:r.id,name:r.name,mode:r.options.mode,random:r.options.random,hard:r.options.hard,capacity:r.capacity,players:r.users.map(u=>({id:u.id,name:u.name})),host:r.users[0]?.id,status:r.game?.status||'waiting'};}
function send(r){const packet=`data: ${JSON.stringify({room:summary(r),game:r.game})}\n\n`;for(const [uid,res]of r.streams){if(res.writableLength>1000000){res.destroy();r.streams.delete(uid);}else res.write(packet);}}
function leave(user){const r=rooms.get(user.room);if(!r)return;const stream=r.streams.get(user.id);if(stream){stream.end();r.streams.delete(user.id);}if(r.game&&r.game.status!=='ended'){r.game.status='ended';r.game.message='플레이어가 퇴장하여 게임이 종료되었습니다.';r.cancelled=true;}r.users=r.users.filter(u=>u.id!==user.id);user.room=null;if(!r.users.length)rooms.delete(r.id);else send(r);}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(req.method==='POST'){const origin=req.headers.origin;const forwardedProto=String(req.headers['x-forwarded-proto']||'').split(',')[0].trim();const expectedOrigin=process.env.PUBLIC_ORIGIN||`${forwardedProto||'http'}://${req.headers.host}`;if(origin&&origin!==expectedOrigin)return json(res,403,{error:'다른 출처의 요청은 허용되지 않습니다.'});}let token=req.headers.cookie?.match(/(?:^|; )session=([a-f0-9]+)/)?.[1],user=sessions.get(token);if(user&&Date.now()-user.seen>86400000){sessions.delete(token);user=null;}if(user)user.seen=Date.now();let body={};if(req.method==='POST'){let chunks='',size=0;for await(const chunk of req){size+=chunk.length;if(size>16000)return json(res,413,{error:'요청이 너무 큽니다.'});chunks+=chunk;}body=JSON.parse(chunks||'{}');}
if(url.pathname==='/api/config')return json(res,200,{clientId});
if(url.pathname==='/api/login'&&req.method==='POST'){if(sessions.size>5000)return json(res,503,{error:'서버가 혼잡합니다.'});let name=String(body.name||'수호자').trim().slice(0,16),uid=id(),google=false;if(body.credential){if(!clientId)return json(res,503,{error:'Google 클라이언트 ID가 설정되지 않았습니다.'});const c=await verifyGoogle(body.credential);uid='g_'+c.sub;name=String(c.name||name).slice(0,16);google=true;}if(user)leave(user);for(const [k,s]of sessions)if(s.id===uid){leave(s);sessions.delete(k);}token=id();user={id:uid,name:name||'수호자',google,seen:Date.now(),room:null};sessions.set(token,user);res.setHeader('Set-Cookie',`session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=86400${process.env.PUBLIC_ORIGIN?.startsWith('https:')?'; Secure':''}`);return json(res,200,{user:{id:user.id,name:user.name,google}});}
if(url.pathname==='/api/me')return json(res,200,{user:user?{id:user.id,name:user.name,google:user.google}:null,room:user?.room&&rooms.has(user.room)?user.room:null});
if(url.pathname==='/api/rankings')return json(res,200,rankings.slice(0,50));
if(url.pathname.startsWith('/api/')&&!user)return json(res,401,{error:'먼저 로그인하세요.'});
if(url.pathname==='/api/rooms'&&req.method==='GET')return json(res,200,[...rooms.values()].filter(r=>r.options.mode!=='single').map(summary));
if(url.pathname==='/api/rooms'&&req.method==='POST'){if(rooms.size>=100)return json(res,503,{error:'방이 가득 찼습니다.'});leave(user);const mode=['single','coop','versus'].includes(body.mode)?body.mode:'single',r={id:id().slice(0,8),name:`${user.name}의 방`,capacity:mode==='single'?1:body.capacity===4?4:2,options:{mode,random:!!body.random,hard:Math.max(0,Math.min(5,Math.floor(Number(body.hard)||0)))},users:[user],streams:new Map(),game:null,created:Date.now()};if(mode==='single')r.game=createGame(r.users,r.options);rooms.set(r.id,r);user.room=r.id;return json(res,200,summary(r));}
if(url.pathname==='/api/join'&&req.method==='POST'){const r=rooms.get(body.id);if(!r||r.game||r.users.length>=r.capacity)return json(res,400,{error:'입장할 수 없는 방입니다.'});leave(user);r.users.push(user);user.room=r.id;send(r);return json(res,200,summary(r));}
if(url.pathname==='/api/leave'&&req.method==='POST'){leave(user);return json(res,200,{});}
if(url.pathname==='/api/events'){const r=rooms.get(user.room);if(!r)return json(res,404,{error:'방을 찾을 수 없습니다.'});res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});r.streams.get(user.id)?.end();r.streams.set(user.id,res);res.write(`data: ${JSON.stringify({room:summary(r),game:r.game})}\n\n`);req.on('close',()=>{if(r.streams.get(user.id)===res)r.streams.delete(user.id);});return;}
if(url.pathname==='/api/action'&&req.method==='POST'){const r=rooms.get(user.room);if(!r)return json(res,404,{error:'방을 찾을 수 없습니다.'});const now=Date.now();if(!user.window||now-user.window>1000){user.window=now;user.requests=0;}if(++user.requests>45)return json(res,429,{error:'잠시 후 다시 시도하세요.'});if(body.type==='launch'){if(r.users[0].id!==user.id||r.users.length!==r.capacity||r.game)return json(res,400,{error:'정원이 모두 입장한 뒤 방장이 시작할 수 있습니다.'});r.game=createGame(r.users,r.options);}else{if(!r.game)return json(res,400,{error:'대기 중입니다.'});if(body.type==='start'&&r.users[0].id!==user.id)return json(res,403,{error:'방장만 전투를 시작할 수 있습니다.'});const error=action(r.game,user.id,body);if(error)return json(res,400,{error});}send(r);return json(res,200,{});}
const staticFiles={'/':'index.html','/app.js':'app.js','/engine.js':'engine.js','/gameplay.js':'gameplay.js','/battle-ui.js':'battle-ui.js','/renderer.js':'renderer.js','/art.js':'art.js','/monster-visuals.js':'monster-visuals.js','/assets/monsters-v4.png':'assets/monsters-v4.png','/assets/monster-reactions-v4.png':'assets/monster-reactions-v4.png','/assets/champions-v3.png':'assets/champions-v3.png','/assets/effects-v3.png':'assets/effects-v3.png','/style.css':'style.css'};const file=staticFiles[url.pathname];if(!file)return json(res,404,{error:'페이지를 찾을 수 없습니다.'});const data=await readFile(new URL(file,import.meta.url));res.writeHead(200,{'Content-Type':file.endsWith('.png')?'image/png':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'});res.end(data);
}catch(e){json(res,400,{error:e.message||'요청 처리 실패'});}});
setInterval(()=>{for(const r of rooms.values()){if(r.game){stepGame(r.game,.1,tick);if(r.game.status==='ended'&&!r.recorded){r.recorded=true;if(!r.cancelled){for(const p of r.game.players)rankings.push({name:p.name,mode:r.game.mode,hard:r.game.hard,random:r.game.random,round:r.game.round,kills:p.kills,seconds:Math.round(r.game.time),date:new Date().toISOString()});rankings.sort((a,b)=>b.round-a.round||b.hard-a.hard||b.kills-a.kills);rankings=rankings.slice(0,200);mkdir(new URL('./data/',import.meta.url),{recursive:true}).then(()=>writeFile(new URL('./data/rankings.json',import.meta.url),JSON.stringify(rankings))).catch(console.error);}}}send(r);if(!r.streams.size&&Date.now()-r.created>3600000)rooms.delete(r.id);}for(const [k,u]of sessions)if(Date.now()-u.seen>86400000){leave(u);sessions.delete(k);}},100);
server.listen(port,'0.0.0.0',()=>console.log(`LOOP DEFENSE · http://localhost:${port}`));
