import {cosmeticArtMarkup} from './cosmetic-art.js';
import {MapArt} from './maps.js';
import {PRODUCTS,SLOTS,productById,equippedProduct,themeFor} from './cosmetics.js';
import {portraitMarkup} from './art.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function cosmeticProfile(name,equipment={},compact=false){const avatar=equippedProduct(equipment,'avatar'),frame=equippedProduct(equipment,'frame'),plate=equippedProduct(equipment,'nameplate'),title=equippedProduct(equipment,'title');return `<div class="cos-profile ${compact?'compact':''}" style="--cos-color:${themeFor(frame).color};--plate-color:${plate?themeFor(plate).color:'#718599'}"><div class="cos-avatar ${frame?'image-framed':''}"><div class="cos-face-window">${portraitMarkup(avatar?.hero??0,'cos-portrait')}</div>${frame?cosmeticArtMarkup(frame,'cos-frame-art'):''}</div><div class="cos-identity"><div class="cos-name ${plate?'image-nameplate':''}">${plate?cosmeticArtMarkup(plate,'cos-plate-art'):''}<strong>${esc(name)}</strong></div>${title?'<div class="cos-title-badge">'+cosmeticArtMarkup(title,'cos-title-art')+'<small>'+esc(title.name)+'</small></div>':''}</div></div>`;}
export function cosmeticPreview(p){const t=themeFor(p),style=`--cos-color:${t.color};--scene:url('${t.scene}')`;if(['avatar','frame','nameplate','title'].includes(p.slot))return `<div class="cos-preview" style="${style}">${cosmeticProfile('수호자',{[p.slot]:p.id})}</div>`;if(p.slot==='map')return `<div class="cos-preview" style="${style}"><canvas class="cos-map-preview" width="400" height="240" data-map-theme="${t.map}"></canvas><div class="cos-map-caption">${t.symbol} ${p.name}</div></div>`;if(p.slot==='lobby')return `<div class="cos-preview scene theme-${t.id}" style="${style}"><div class="cos-scene-label">${t.symbol}<strong>${p.name}</strong></div></div>`;return `<div class="cos-preview premium-preview ${p.slot}" style="${style}"><div class="cos-light-rays"></div>${cosmeticArtMarkup(p,'cos-premium-art')}<span class="cos-effect-caption">${p.slot==='emote'?['좋아요!','헉!','최고야!','맡겨줘!','고마워요!','승리!'][['forest','frost','ember','arcane','ocean','royal'].indexOf(p.theme)]:p.slot==='victory'?'VICTORY':p.slot==='entry'?'GUARDIAN ARRIVES':p.slot==='kill'?'FINISH':'SUMMON'}</span></div>`;}

export function applyProfile(equipment={},name){const profile=document.querySelector('.sidebar .profile');if(!profile)return;profile.querySelector('.cos-profile')?.remove();const avatar=profile.querySelector('.avatar');if(avatar)avatar.hidden=true;const userName=profile.querySelector('#user-name');if(userName)userName.parentElement.hidden=true;profile.insertAdjacentHTML('afterbegin',cosmeticProfile(name||'수호자',equipment,true));}
export async function mountShop(root,api,onEquip){let state={owned:[],equipped:{}},category='all',search='',ownedOnly=false,selected=PRODUCTS[0].id,busy=false,loaded=false;root.innerHTML=`<section class="shop-screen"><div class="shop-banner"><span>THE GUARDIAN’S COLLECTION · TEST COLLECTION</span><h1>상점</h1><div class="shop-intro">당신의 수호자를 위한 특별한 취향.</div><p>전 상품 <b>0 ◆ 무료</b> · 외형 전용 · 능력치 변화 없음</p><small>보유 다이아 <b id="diamond-balance">—</b> ◆</small></div><div class="shop-layout"><section class="shop-catalog"><div class="cos-toolbar"><select id="cos-category" aria-label="상품 종류"><option value="all">전체 상품 (${PRODUCTS.length})</option>${Object.entries(SLOTS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><input id="cos-search" placeholder="상품 이름 검색" aria-label="상품 검색"><label><input type="checkbox" id="cos-owned"> 보유 상품만</label></div><div class="shop-category-tabs">${[["all","전체"],["frame","프로필 테두리"],["avatar","초상화"],["lobby","대기실 배경"],["map","전장 테마"],["entry","입장 연출"],["summon","소환진"]].map(([k,v])=>`<button data-shop-category="${k}" aria-pressed="${k==='all'}">${v}</button>`).join('')}</div><p class="cos-status" role="status">보관함을 불러오고 있습니다…</p><div class="cos-grid"></div></section><aside class="shop-detail" id="cos-detail"></aside></div></section>`;
 const status=root.querySelector('.cos-status');
 function render(){root.querySelectorAll('[data-shop-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.shopCategory===category)));const list=PRODUCTS.filter(p=>(category==='all'||p.slot===category)&&p.name.includes(search)&&(!ownedOnly||state.owned.includes(p.id)));if(list.length&&!list.some(p=>p.id===selected))selected=list[0].id;root.querySelector('.cos-grid').innerHTML=list.map(p=>`<button class="cos-product ${p.id===selected?'selected':''}" data-product="${p.id}">${cosmeticPreview(p)}<small>${SLOTS[p.slot]}</small><strong>${p.name}</strong><span>${state.equipped[p.slot]===p.id?'✓ 장착 중':state.owned.includes(p.id)?'보유 중':'0 ◆ 무료'}</span></button>`).join('')||'<p>조건에 맞는 상품이 없습니다.</p>';const p=productById(selected),owns=state.owned.includes(p.id),equipped=state.equipped[p.slot]===p.id;root.querySelector('#cos-detail').innerHTML=`<span class="eyebrow">COLLECTION PREVIEW</span><h2>${p.name}</h2>${cosmeticPreview(p)}<p>${SLOTS[p.slot]} · ${p.location}</p><p class="muted">구매한 상품은 계정 보관함에 영구 저장됩니다.<br>테스트 가격: <strong>0 다이아</strong></p><button class="primary" id="cos-buy" ${busy||!loaded?'disabled':''}>${busy?'저장 중…':equipped?'장착 해제':owns?'장착하기':'0 ◆ 무료 구매'}</button><small>무료 구매 후 장착하기를 눌러 적용하세요.</small>`;paintMapPreviews();}
 root.querySelector('#cos-category').onchange=e=>{category=e.target.value;render();};root.querySelector('#cos-search').oninput=e=>{search=e.target.value.trim();render();};root.querySelector('#cos-owned').onchange=e=>{ownedOnly=e.target.checked;render();};root.onclick=async e=>{const tab=e.target.closest('[data-shop-category]');if(tab){category=tab.dataset.shopCategory;root.querySelector('#cos-category').value=category;render();return;}const p=e.target.closest('[data-product]');if(p){selected=p.dataset.product;render();return;}if(!e.target.closest('#cos-buy')||busy||!loaded)return;const item=productById(selected),owns=state.owned.includes(item.id);busy=true;render();try{state=await api(owns?'cosmetics/equip':'cosmetics/purchase',owns?{slot:item.slot,item:state.equipped[item.slot]===item.id?null:item.id}:{item:item.id});status.textContent=owns?'장착 상태를 저장했습니다.':'무료 구매 완료! 장착하기를 눌러 사용하세요.';if(owns)onEquip(state.equipped);}catch(err){status.textContent=err.message;}finally{busy=false;if(root.querySelector('.cos-grid'))render();}};
 render();try{const [inventory,wallet]=await Promise.all([api('cosmetics'),api('wallet')]);state=inventory;if(!root.querySelector('.cos-grid'))return;loaded=true;root.querySelector('#diamond-balance').textContent=wallet.diamonds.toLocaleString();status.textContent=`${PRODUCTS.length}종 · 보유 ${state.owned.length}종 · 테스트 무료 판매 중`;render();}catch(e){if(root.querySelector('.cos-grid')){status.textContent=e.message;if(e.message.includes('로그인')){const login=document.createElement('button');login.className='mini-btn';login.textContent='Google 로그인';login.onclick=()=>document.querySelector('#login')?.showModal();status.append(' ',login);}} }
}
export function lobbyCosmetics(p){const item=equippedProduct(p?.cosmetics,'lobby'),entry=equippedProduct(p?.cosmetics,'entry');return {style:item?`--scene:url('${themeFor(item).scene}');--cos-color:${themeFor(item).color}`:'',className:item?'cos-lobby theme-'+item.theme:'',entry:entry?`<div class="cos-entry" style="--cos-color:${themeFor(entry).color}">${cosmeticArtMarkup(entry,'cos-entry-art')}<span class="cos-entry-caption">${themeFor(entry).name}</span></div>`:''};}

let previewArt;function paintMapPreviews(){if(!previewArt){previewArt=new MapArt();previewArt.image.addEventListener('load',paintMapPreviews);previewArt.road.addEventListener('load',paintMapPreviews);}for(const canvas of document.querySelectorAll('.cos-map-preview')){const ctx=canvas.getContext('2d');previewArt.active=undefined;const theme=previewArt.draw(ctx,Number(canvas.dataset.mapTheme)*10+1,10,true);previewArt.drawRoad(ctx,theme);}}

export async function openWardrobe(api,onEquip,name){
 if(document.querySelector('#account-wardrobe'))return;
 const dialog=document.createElement('dialog');dialog.id='account-wardrobe';
 const tabs={all:'전체',profile:'프로필',nameplate:'명패',entry:'입장 연출',summon:'소환진',other:'기타'};
 dialog.innerHTML='<header><div><small>MY COLLECTION</small><h2 id="wardrobe-title">내 꾸미기 보관함</h2></div><button data-close aria-label="보관함 닫기">닫기 ×</button></header><div class="wardrobe-layout"><section class="wardrobe-catalog"><div class="wardrobe-toolbar"><nav aria-label="꾸미기 종류">'+Object.entries(tabs).map(([k,v])=>'<button data-category="'+k+'" aria-pressed="'+(k==='all')+'">'+v+'</button>').join('')+'</nav><input type="search" aria-label="보유한 꾸미기 검색" placeholder="⌕  보유한 꾸미기 검색하기…"></div><div class="wardrobe-grid"></div></section><aside class="wardrobe-detail"></aside></div><p class="wardrobe-status" role="status">보관함을 불러오는 중…</p>';
 dialog.setAttribute('aria-labelledby','wardrobe-title');document.body.append(dialog);dialog.showModal();dialog.addEventListener('close',()=>dialog.remove());dialog.querySelector('[data-close]').onclick=()=>dialog.close();
 let state={owned:[],equipped:{}},busy=false,selected=null,category='all',search='';
 const status=dialog.querySelector('[role=status]');
 const matches=p=>category==='all'||(category==='profile'?['avatar','frame','title'].includes(p.slot):category==='other'?['lobby','map','kill','victory','emote'].includes(p.slot):p.slot===category);
 function art(p){if(['frame','nameplate','title'].includes(p.slot))return '<div class="wardrobe-object '+p.slot+'">'+cosmeticArtMarkup(p)+(p.slot==='nameplate'?'<strong>'+esc(name)+'</strong>':p.slot==='title'?'<strong>'+esc(p.name)+'</strong>':'')+'</div>';return cosmeticPreview(p);}
 function render(){
 const items=PRODUCTS.filter(p=>state.owned.includes(p.id)&&matches(p)&&p.name.includes(search));
 if(!items.some(p=>p.id===selected))selected=items[0]?.id;
 dialog.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===category)));
 dialog.querySelector('.wardrobe-grid').innerHTML=items.map(p=>'<button class="wardrobe-card '+(p.id===selected?'selected':'')+'" data-product="'+p.id+'" aria-pressed="'+(p.id===selected)+'"><div class="wardrobe-card-art">'+art(p)+'</div>'+(state.equipped[p.slot]===p.id?'<span class="wardrobe-equipped">✓ 장착 중</span>':'')+'<div class="wardrobe-card-text"><small>'+SLOTS[p.slot]+'</small><strong>'+esc(p.name)+'</strong></div></button>').join('')||'<div class="wardrobe-empty">'+(state.owned.length?'검색 조건에 맞는 꾸미기가 없습니다.':'아직 보유한 꾸미기가 없습니다.<br>상점에서 마음에 드는 상품을 찾아보세요.')+'</div>';
 const p=productById(selected),equipped=p&&state.equipped[p.slot]===p.id;
 dialog.querySelector('.wardrobe-detail').innerHTML='<h3>장착 미리보기</h3><div class="wardrobe-stage">'+(p&&!['avatar','frame','nameplate','title'].includes(p.slot)?art(p):cosmeticProfile(name,p?{...state.equipped,[p.slot]:p.id}:state.equipped))+'</div><div class="wardrobe-description">'+(p?'<h2>'+esc(p.name)+'</h2><small>'+SLOTS[p.slot]+'</small><p>'+esc(p.location)+'에 표시됩니다.</p><button class="wardrobe-equip" '+(busy?'disabled':'')+'>'+(busy?'저장 중…':equipped?'장착 해제':'장착하기')+'</button>':'<h2>나만의 수호자를 꾸며보세요</h2>')+'<div class="wardrobe-saved">✓ 변경 사항이 자동 저장됩니다.</div></div>';
 paintMapPreviews();
 }
 dialog.querySelector('input').oninput=e=>{search=e.target.value.trim();render();};
 dialog.addEventListener('click',async e=>{
 const tab=e.target.closest('[data-category]');if(tab){category=tab.dataset.category;render();return;}
 const card=e.target.closest('[data-product]');if(card){selected=card.dataset.product;render();return;}
 if(!e.target.closest('.wardrobe-equip')||busy)return;
 const item=productById(selected);if(!item)return;busy=true;render();
 try{state=await api('cosmetics/equip',{slot:item.slot,item:state.equipped[item.slot]===item.id?null:item.id});onEquip(state.equipped);status.textContent='장착 상태를 저장했습니다.';}catch(error){status.textContent=error.message;}finally{busy=false;if(dialog.isConnected)render();}
 });
 render();try{state=await api('cosmetics');if(!dialog.isConnected)return;status.textContent='보유 상품 '+state.owned.length+'종 · 장착 변경은 계정에 저장됩니다.';render();}catch(error){status.textContent=error.message;}
}
