import test from 'node:test';import assert from 'node:assert/strict';
import {createGame,recordDamage,updateDps,castSupport,stats,tick} from './engine.js';
import {gameForPlayer} from './game-view.js';
const c=(id,base=0,tier=0)=>({id,base,tier,x:180+id*50,y:200,equipment:{},growth:0,cd:0});
test('five-second DPS sums actual damage and decays while idle',()=>{const g=createGame([{id:'a'}]);const hero=c(1);g.players[0].champions=[hero];recordDamage(hero,50,1);recordDamage(hero,25,2);g.time=3;updateDps(g);assert.equal(hero.dps,15);g.time=7;updateDps(g);assert.equal(hero.dps,0);});
test('private DPS and internal history never reach other players including reconnect snapshot',()=>{const g=createGame([{id:'a'},{id:'b'}]);g.players.forEach((p,i)=>p.champions=[{...c(i),dps:42,damageLog:[{time:1,amount:210}]}]);const view=gameForPlayer(g,'a');assert.equal(view.players[0].champions[0].dps,42);assert.equal(view.players[1].champions[0].dps,undefined);assert.equal(view.players[0].champions[0].damageLog,undefined);assert.equal(g.players[1].champions[0].dps,42);});
test('overkill is excluded from DPS and buff expires after ten seconds',()=>{const g=createGame([{id:'a'}]);const hero=c(1);g.players[0].champions=[hero];g.status='playing';g.round=1;g.boards[0].round=1;g.boards[0].monsters=[{id:99,p:.15,hp:1,maxHp:1,speed:0,slow:0,stun:0,shred:0,poison:0,defenses:[]}];tick(g,.05);assert.equal(hero.dps,.2);hero.supportBuffs={damage:{amount:.3,until:1}};g.time=2;tick(g,.05);assert.equal(hero.supportBuffs.damage,undefined);});

test('oracle randomly chooses unbuffed allies and never refreshes or stacks active buffs',()=>{const g=createGame([{id:'a'}]),p=g.players[0],support=c(1,9),weak=c(2),strong=c(3,0,4);p.champions=[support,weak,strong];castSupport(g,[p],support,()=>0);assert.ok(weak.supportBuffs.damage);assert.equal(strong.supportBuffs,undefined);const original={...weak.supportBuffs.damage};castSupport(g,[p],support,()=>1);assert.ok(strong.supportBuffs.speed);assert.deepEqual(weak.supportBuffs.damage,original);assert.equal(castSupport(g,[p],support,()=>0),false);g.time=10;assert.equal(castSupport(g,[p],support,()=>1),true);assert.equal(strong.supportBuffs.speed.until,20);});
