import test from 'node:test';import assert from 'node:assert/strict';
import {TALENTS,grantTalentOffers,chooseTalent,talentTotals,drawCost,upgradeCost} from './talents.js';
import {createGame,action,tick,stats,damage,castSupport} from './engine.js';
const hero=()=>({id:1,base:0,tier:4,x:400,y:140,equipment:{}});
test('42 unique talents and 20 selections through round100 never repeat owned cards or duplicate offers',()=>{assert.equal(TALENTS.length,42);assert.equal(new Set(TALENTS.map(c=>c.id)).size,42);for(let seed=1;seed<=30;seed++){let n=seed;const rng=()=>((n=(n*1664525+1013904223)>>>0)/4294967296),g=createGame([{id:'a'}]),p=g.players[0];p.champions=[hero()];g.status='playing';for(let round=1;round<=100;round++){g.round=round;grantTalentOffers(g,rng);if(round%5){assert.equal(p.talentOffers?.length||0,0);continue;}assert.equal(g.status,'playing');assert.equal(p.talentOffers.length,1);const offer=p.talentOffers[0];assert.equal(new Set(offer.choices).size,3);assert.ok(offer.choices.every(id=>!p.talents?.includes(id)));assert.ok(offer.choices.every(id=>!id.startsWith('mastery')||id==='mastery0'));grantTalentOffers(g,rng);assert.equal(p.talentOffers.length,1);assert.equal(action(g,'a',{type:'talent',index:Math.floor(rng()*3)}),undefined);assert.equal(g.status,'playing');}assert.equal(p.talents.length,20);assert.equal(p.champions[0].talents.length,20);}});
test('actual wave5 keeps fighting while awaiting choice; invalid and duplicate choices do not mutate',()=>{const g=createGame([{id:'a'}]);g.round=4;g.status='playing';g.boards[0].round=4;tick(g,.05);assert.equal(g.round,5);assert.equal(g.status,'playing');const p=g.players[0],gold=p.gold,time=g.time;tick(g,.05);assert.ok(g.time>time);assert.match(action(g,'a',{type:'talent',id:'fake'}),/선택/);assert.equal(p.gold,gold);const id=p.talentOffers[0].choices[0];action(g,'a',{type:'talent',index:0});assert.match(action(g,'a',{type:'talent',id}),/선택/);assert.equal(p.talents.length,1);});
test('online offers queue without pause and apply only to choosing player; queued cards refill after duplicates removed',()=>{for(const mode of ['coop','versus']){const g=createGame([{id:'a'},{id:'b'}],{mode});g.status='playing';for(const round of [5,10,15]){g.round=round;grantTalentOffers(g,()=>0);}assert.equal(g.status,'playing');const p=g.players[0];assert.equal(p.talentOffers.length,3);for(let i=0;i<3;i++){chooseTalent(g,p,p.talentOffers[0].choices[0]);for(const offer of p.talentOffers){assert.equal(new Set(offer.choices).size,3);assert.ok(offer.choices.every(id=>!p.talents.includes(id)));}}assert.equal(g.players[1].talents,undefined);assert.equal(g.players[1].talentOffers.length,3);}});
test('discounts charge real costs, new summons inherit talents, mastery stats and caps are finite',()=>{const g=createGame([{id:'a'}]),p=g.players[0];p.talents=['heroDiscount','itemDiscount','upgradeDiscount','attack','mastery0'];assert.equal(drawCost(p,'hero'),28);assert.equal(drawCost(p,'item'),28);assert.equal(upgradeCost(p,'hero'),32);p.gold=28;assert.equal(action(g,'a',{type:'draw',kind:'hero'}),undefined);assert.equal(p.gold,0);assert.deepEqual(p.champions[0].talents,p.talents);const plain=stats(hero()),strong=stats({...hero(),talents:p.talents});assert.ok(Math.abs(strong.attack/plain.attack-1.18)<1e-8);p.gold=32;action(g,'a',{type:'upgrade',kind:'hero'});assert.equal(p.gold,0);assert.equal(p.heroLevel,2);const all=stats({...hero(),talents:TALENTS.map(c=>c.id)});assert.ok(Object.values(all).every(Number.isFinite));assert.ok(all.crit<=.85);assert.ok(all.range<=550);assert.ok(all.skillCooldown<=.2);assert.deepEqual(talentTotals(['attack','attack']),talentTotals(['attack']));});
test('instant gold once, boss bonus in damage, cooldown talent in actual casting clock',()=>{const g=createGame([{id:'a'}]),p=g.players[0];p.talentOffers=[{round:5,choices:['funds','attack','boss']}];chooseTalent(g,p,'funds');assert.equal(p.gold,105);chooseTalent(g,p,'funds');assert.equal(p.gold,105);const s=stats({...hero(),talents:['boss']});assert.ok(Math.abs(damage({boss:true,defenses:[]},100,'물리원거리',s)-110)<1e-8);p.champions=[{...hero(),talents:['cooldown']}];g.status='playing';g.round=1;g.boards[0].round=1;g.boards[0].monsters=[{id:9,p:.1,hp:1e9,maxHp:1e9,speed:0,family:0,defenses:[],slow:0,stun:0,shred:0,poison:0}];tick(g,.05);assert.ok(Math.abs(p.champions[0].skillReadyAt-(g.time+15*.94))<1e-8);});
