import test from 'node:test';import assert from 'node:assert/strict';
import {createGame,action,tick,monster,boardOwners,championBoard,castSupport} from './engine.js';
import {gameForPlayer} from './game-view.js';import {grantTalentOffers,upgradeCost} from './talents.js';
const users=[{id:'a',name:'A'},{id:'b',name:'B'}];
const hero=(id,base=0)=>({id,base,tier:0,x:400,y:145,cd:0,equipment:{}});
function coop(){const g=createGame(users,{mode:'coop'});g.status='playing';g.round=4;g.boards.forEach(b=>b.round=4);tick(g,.05);return g;}
test('sale pays 15 once, returns all equipment, rejects foreign heroes and full inventory',()=>{const g=createGame(users),p=g.players[0],c=hero(1);c.equipment={0:{id:3,base:0,tier:1}};p.champions=[c];assert.match(action(g,'b',{type:'sell',id:1}),/내 챔피언/);p.items=Array.from({length:80},(_,i)=>({id:10+i,base:0,tier:0}));assert.match(action(g,'a',{type:'sell',id:1}),/공간/);p.items=[];action(g,'a',{type:'sell',id:1});assert.equal(p.gold,75);assert.equal(p.items[0].id,3);assert.equal(p.champions.length,0);action(g,'a',{type:'sell',id:1});assert.equal(p.gold,75);assert.equal(upgradeCost(p,'hero'),35);});
test('coop has personal boards plus world boss, 30 normal enemies each, deadline defeat',()=>{const g=coop();assert.equal(g.boards.length,3);for(const b of g.boards.slice(0,2)){assert.equal(b.spawn.length,30);assert.ok(b.spawn.every(m=>!m.boss));}const w=g.boards[2];assert.equal(w.monsters.length,1);assert.equal(w.monsters[0].worldBoss,true);assert.ok(w.monsters[0].hp>monster(g,{round:5,boss:true}).hp);g.boards.slice(0,2).forEach(b=>{b.spawn=[];b.monsters=[];});tick(g,.1);assert.equal(g.round,6);assert.equal(g.status,'playing');assert.equal(w.expiresRound,10);while(g.round<9){g.boards.slice(0,2).forEach(b=>{b.spawn=[];b.monsters=[];});tick(g,.01);}g.boards.slice(0,2).forEach(b=>{b.spawn=[];b.monsters=[];});tick(g,.01);assert.equal(g.status,'ended');assert.match(g.message,/월드보스/);});
test('shared 100 monster limit counts every personal board',()=>{const g=createGame(users,{mode:'coop'});g.status='playing';g.round=1;g.boards.forEach(b=>b.round=1);for(const b of g.boards.slice(0,2))b.monsters=Array.from({length:50},()=>monster(g,{round:1,boss:false}));tick(g,.01);assert.equal(g.status,'ended');assert.match(g.message,/100/);});
test('dispatch moves combat ownership, support stays on board, victory returns champions',()=>{const g=coop(),p=g.players[0],q=g.players[1],c=hero(100),support=hero(101,9),other=hero(102);p.champions=[c,support];q.champions=[other];assert.equal(boardOwners(g,0)[0].champions.length,2);action(g,'a',{type:'dispatch',id:c.id});assert.equal(championBoard(g,c),2);assert.equal(boardOwners(g,0)[0].champions.length,1);assert.equal(castSupport(g,boardOwners(g,0),support),false);action(g,'b',{type:'dispatch',id:other.id});assert.equal(boardOwners(g,2).flatMap(p=>p.champions).length,2);const before=g.boards[2].monsters[0].hp;tick(g,.05);assert.ok(g.boards[2].monsters[0].hp<before);g.boards[2].monsters[0].hp=0;g.boards[2].monsters[0].lastHit='a';tick(g,.05);assert.equal(c.world,false);assert.equal(other.world,false);assert.equal(p.gold,90);assert.equal(q.gold,60);});
test('gold support is atomic and cannot overspend or target yourself',()=>{const g=coop();for(const amount of [-1,0,61,1.5,NaN,Infinity])assert.ok(action(g,'a',{type:'donate',to:'b',amount}));assert.ok(action(g,'a',{type:'donate',to:'a',amount:10}));action(g,'a',{type:'donate',to:'b',amount:10});assert.deepEqual(g.players.map(p=>p.gold),[50,70]);});

test('round five no longer grants trait cards',()=>{const g=createGame(users);g.round=4;g.status='playing';g.boards.forEach(b=>b.round=4);tick(g,.05);assert.equal(g.round,5);assert.ok(g.players.every(p=>!p.talentOffers?.length));assert.equal(g.status,'playing');});
